---
extends: default
rules:
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  line-length:
    max: 120
  indentation:
    spaces: 2
  comments-indentation: disable
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
