---
extends: default

rules:
  comments:
    require-starting-space: true
    min-spaces-from-content: 1

  line-length:
    max: 120 # Increase if longer comments cause issues

  indentation:
    spaces: 2 # Use 2-space indentation

  comments-indentation: disable # Disable if comment alignment is strict
