#!/usr/bin/env bash

set -e

if ! [ -x "$(command -v ansible)" ]; then
	echo "Installing Ansible..."
	sudo apt-add-repository -y ppa:ansible/ansible
	sudo apt-get update -y
	sudo apt-get install -y curl git software-properties-common ansible
fi

if ! ansible-galaxy collection list | grep -q 'community.general'; then
	echo "Installing community.general collection..."
	ansible-galaxy collection install community.general
fi

ROOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOSTS="$ROOTDIR/hosts"
PLAYBOOK="$ROOTDIR/setup.yml"

ansible-playbook -i "$HOSTS" "$PLAYBOOK" --ask-become-pass --ask-vault-pass

if command -v terminal-notifier 1>/dev/null 2>&1; then
	terminal-notifier -title "Ansible: Bootstrap complete" -message "Successfully set up dev environment."
fi

exit 0
