- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  become: true
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
      - install
      - core
  tasks:
  - include: tasks/ssh.yml
  - include: tasks/core.yml
  - include: tasks/zsh.yml
  - include: tasks/alacritty.yml
  - include: tasks/fonts.yml
  - include: tasks/tmux.yml
  - include: tasks/node.yml
  - include: tasks/npm-packages.yml
  - include: tasks/pip-packages.yml
  - include: tasks/neovim.yml
  # - include: tasks/docker.yml
  # - include: tasks/kubectl.yml
  # - include: tasks/helm.yml
  - include: tasks/bazel.yml
  # - include: tasks/dwm.yml
  # - include: tasks/dotfiles.yml
  - include: tasks/brave.yml
  # - include: tasks/spotify.yml

