---
- hosts: localhost
  become: true
  vars:
    main_user: "{{ lookup('env', 'USER') }}"
    main_user_dir: "/home/{{ lookup('env', 'USER') }}"
    rsa_source_key: "./.ssh/id_rsa"
    rsa_dest_key: "/home/{{  lookup('env', 'USER')  }}/.ssh/id_rsa"
    source_key: "./.ssh/id_ed25519"
    dest_key: "/home/{{  lookup('env', 'USER')  }}/.ssh/id_ed25519"
  pre_tasks:
    - name: Pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: false
      when: ansible_distribution == "Archlinux"

    - name: Pre-run | update package cache (debian)
      tags: always
      apt: update_cache=yes
      changed_when: false
      when: ansible_distribution == ["Debian", "Ubuntu"]

  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/rust.yml
    - include_tasks: tasks/alacritty.yml
    - include_tasks: tasks/fonts.yml
    - include_tasks: tasks/tmux.yml
    - include_tasks: tasks/node.yml
    - include_tasks: tasks/npm-packages.yml
    - include_tasks: tasks/pip-packages.yml
    - include_tasks: tasks/neovim.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/barrier.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/kubectl.yml
    - include_tasks: tasks/helm.yml
    - include_tasks: tasks/bazel.yml
    - include_tasks: tasks/cpp.yml
    - include_tasks: tasks/cargo.yml
    - include_tasks: tasks/snap.yml
    - include_tasks: tasks/misc.yml
    - include_tasks: tasks/lazygit.yml
    - include_tasks: tasks/keyboard-ergodox.yml
    - include_tasks: tasks/brave.yml
    # - include_tasks: tasks/spotify.yml
    - include_tasks: tasks/discord.yml
    - include_tasks: tasks/obsidian.yml
    - include_tasks: tasks/gtk.yml
    # - include_tasks: tasks/theme_nord.yml
    # - include_tasks: tasks/theme_tokyonight.yml
    # - include_tasks: tasks/firefox.yml
    - include_tasks: tasks/grub.yml
    # - include_tasks: tasks/dwm.yml
    - include_tasks: tasks/restart.yml
