---
- hosts: localhost
  become: true
  vars:
    main_user: "{{ lookup('env', 'USER') }}"
    main_user_dir: "/home/{{ lookup('env', 'USER') }}"
    source_key: "./.ssh/id_rsa"
    dest_key: "/home/{{  lookup('env', 'USER')  }}/.ssh/id_rsa"
    discord:
      version: 0.0.16
      libfixed: false
  pre_tasks:
    - name: Pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: Pre-run | update package cache (debian)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution == ["Debian", "Ubuntu"]

  tasks:
  - include: tasks/ssh.yml
  - include: tasks/core.yml
  - include: tasks/alacritty.yml
  - include: tasks/fonts.yml
  - include: tasks/tmux.yml
  - include: tasks/node.yml
  - include: tasks/npm-packages.yml
  - include: tasks/pip-packages.yml
  - include: tasks/neovim.yml
  - include: tasks/zsh.yml
  - include: tasks/barrier.yml
  - include: tasks/dotfiles.yml
  - include: tasks/docker.yml
  - include: tasks/kubectl.yml
  - include: tasks/helm.yml
  - include: tasks/bazel.yml
  - include: tasks/cpp.yml
  - include: tasks/brave.yml
  - include: tasks/spotify.yml
  - include: tasks/discord.yml
  - include: tasks/gtk.yml
  - include: tasks/dwm.yml
  - include: tasks/restart.yml
