---
- hosts: localhost
  become: true
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
  vars_files:
    - vars/vars.yml
  handlers:
    - name: update desktop database
      ansible.builtin.command:
        cmd: update-desktop-database
      changed_when: false

  pre_tasks:
    - ansible.builtin.include_tasks: tasks/pre/ssh.yml
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
    - name: Check if running in container
      ansible.builtin.stat:
        path: /.dockerenv
      register: container_check
    - ansible.builtin.include_tasks: tasks/pre/core.yml
    - ansible.builtin.include_tasks: tasks/pre/cargo.yml
    - ansible.builtin.include_tasks: tasks/pre/cpp.yml
    - ansible.builtin.include_tasks: tasks/pre/fonts.yml
    - ansible.builtin.include_tasks: tasks/pre/go.yml
    - ansible.builtin.include_tasks: tasks/pre/lazygit.yml
    - ansible.builtin.include_tasks: tasks/pre/lua.yml
    - ansible.builtin.include_tasks: tasks/pre/neovim.yml
    - ansible.builtin.include_tasks: tasks/pre/npm_packages.yml
    - ansible.builtin.include_tasks: tasks/pre/python.yml
    - ansible.builtin.include_tasks: tasks/pre/tmux.yml
    - ansible.builtin.include_tasks: tasks/pre/zsh.yml
    - ansible.builtin.include_tasks: tasks/pre/dotfiles.yml
  tasks:
    - ansible.builtin.include_tasks: tasks/post/ai.yml
    - ansible.builtin.include_tasks: tasks/post/alacritty.yml
    - ansible.builtin.include_tasks: tasks/post/bazel.yml
    - ansible.builtin.include_tasks: tasks/post/discord.yml
    - ansible.builtin.include_tasks: tasks/post/docker.yml
    - ansible.builtin.include_tasks: tasks/post/grub.yml
    - ansible.builtin.include_tasks: tasks/post/immersed.yml
    - ansible.builtin.include_tasks: tasks/post/keyboard.yml
    - ansible.builtin.include_tasks: tasks/post/pdf_reader.yml
    - ansible.builtin.include_tasks: tasks/post/ranger.yml
    - ansible.builtin.include_tasks: tasks/post/snap.yml
  post_tasks:
    - ansible.builtin.include_tasks: tasks/theme/gnome.yml
    - ansible.builtin.include_tasks: tasks/theme/gsettings.yml
    - ansible.builtin.include_tasks: tasks/theme/gtk.yml
    - ansible.builtin.include_tasks: tasks/theme/i3.yml
