---
- hosts: localhost
  become: true
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
  vars_files:
    - vars/vars.yml

  pre_tasks:
    - ansible.builtin.include_tasks: tasks/core.yml
    - ansible.builtin.include_tasks: tasks/ssh.yml
    - name: Check if running in container
      ansible.builtin.stat:
        path: /.dockerenv
      register: container_check
    - ansible.builtin.include_tasks: tasks/pre/aur.yml
    - ansible.builtin.include_tasks: tasks/pre/cargo.yml
    - ansible.builtin.include_tasks: tasks/pre/cpp.yml
    - ansible.builtin.include_tasks: tasks/pre/fonts.yml
    - ansible.builtin.include_tasks: tasks/pre/go.yml
    - ansible.builtin.include_tasks: tasks/pre/lazygit.yml
    - ansible.builtin.include_tasks: tasks/pre/lua.yml
    - ansible.builtin.include_tasks: tasks/pre/neovim.yml
    - ansible.builtin.include_tasks: tasks/pre/npm_packages.yml
    - ansible.builtin.include_tasks: tasks/pre/python.yml
    - ansible.builtin.include_tasks: tasks/pre/snap.yml
    - ansible.builtin.include_tasks: tasks/pre/tmux.yml
    - ansible.builtin.include_tasks: tasks/pre/zsh.yml
    - ansible.builtin.include_tasks: tasks/pre/dotfiles.yml
  tasks:
    - ansible.builtin.include_tasks: tasks/post/ai.yml
    - ansible.builtin.include_tasks: tasks/post/alacritty.yml
    - ansible.builtin.include_tasks: tasks/post/bazel.yml
    - ansible.builtin.include_tasks: tasks/post/discord.yml
    - ansible.builtin.include_tasks: tasks/post/docker.yml
    - ansible.builtin.include_tasks: tasks/post/grub.yml
    - ansible.builtin.include_tasks: tasks/post/office.yml
    - ansible.builtin.include_tasks: tasks/post/ranger.yml
    - ansible.builtin.include_tasks: tasks/post/vpn.yml
  post_tasks:
    - ansible.builtin.include_tasks: tasks/theme/gnome.yml
    - ansible.builtin.include_tasks: tasks/theme/gsettings.yml
    - ansible.builtin.include_tasks: tasks/theme/gtk.yml
    - ansible.builtin.include_tasks: tasks/apps/brave.yml
    - ansible.builtin.include_tasks: tasks/apps/deskflow.yml
    - ansible.builtin.include_tasks: tasks/apps/immersed.yml
    - ansible.builtin.include_tasks: tasks/apps/keyboard.yml
