#!/usr/bin/env bash

docker rmi -f new-computer 2>/dev/null
docker build . -f test.Dockerfile -t new-computer
echo "Ansible become pass: ansible"
echo "docker run -it --rm --name new-computer new-computer:latest /bin/bash"
