- name: Ensure alacritty apt repo is present
  apt_repository:
    repo: 'ppa:mmstick76/alacritty'
    state: present
  become: yes
  tags:
  - install
  - terminal
  - alacritty
- name: Install alacritty
  apt:
    name: alacritty
  become: yes
  tags:
  - install
  - terminal
  - alacritty
