---
- name: Install Alacritty deps
  become: true
  apt:
    pkg:
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
  tags:
    - terminal
    - alacritty
- name: Install Alacritty
  community.general.cargo:
    name: alacritty
  tags:
    - terminal
    - alacritty
- name: Make Alacritty default terminal
  shell: >-
    update-alternatives --install /usr/bin/x-terminal-emulator
    x-terminal-emulator /usr/bin/alacritty 60
  become: true
  tags:
    - terminal
    - alacritty
