---
- name: Ensure alacritty apt repo is present
  apt_repository:
    repo: 'ppa:mmstick76/alacritty'
    state: present
  become: true
  tags:
    - terminal
    - alacritty
- name: Install alacritty
  apt:
    name: alacritty
  become: true
  tags:
    - terminal
    - alacritty
- name: Make Alacritty default terminal
  shell: update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/alacritty 60
  become: true
  tags:
    - terminal
    - alacritty
