---
- name: Install Alacritty deps
  become: true
  apt:
    pkg:
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
  tags:
    - terminal
    - alacritty
- name: Install Alacritty
  community.general.cargo:
    name: alacritty
  tags:
    - terminal
    - alacritty
- name: Symbolic link alacritty
  become: true
  file:
    src: "{{ main_user_dir }}/.cargo/bin/alacritty"
    dest: "/usr/bin/alacritty"
    state: link
  tags:
    - bazel
- name: Make Alacritty default terminal
  become: true
  shell: >-
    update-alternatives --install /usr/bin/x-terminal-emulator
    x-terminal-emulator /usr/bin/alacritty 60
  tags:
    - terminal
    - alacritty
- name: Copy alacritty icon
  become: true
  copy:
    src: "files/alacritty-simple.svg"
    dest: /usr/share/pixmaps/Alacritty.svg
    mode: 0644
  tags:
    - terminal
    - alacritty
- name: Create alacritty desktop entry
  become: true
  shell: desktop-file-install files/Alacritty.desktop && update-desktop-database
  tags:
    - terminal
    - alacritty
