---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  tags:
  - barrier
- name: Install barrier
  apt:
    name: ["rclone", "barrier"]
  become: true
  tags:
  - barrier
