---
- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  tags:
    - barrier

- name: Install barrier
  ansible.builtin.apt:
    name: ["rclone", "barrier"]
  become: true
  tags:
    - barrier
