---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: true
    update_cache: true
  tags:
    - barrier
- name: Install barrier
  apt:
    name: ["rclone", "barrier"]
  become: true
  tags:
    - barrier
