- name: Install Bazel
  npm:
    name: "@bazel/bazelisk"
    global: true
  tags:
  - bazel
- name: Install bazel compilation database
  shell: curl -L "https://github.com/grailbio/bazel-compilation-database/archive/0.4.5.tar.gz" | tar -xz && ln -f -s "/usr/bin/local/bazel-compilation-database-0.4.5/generate.sh" bazel-compdb
  tags:
  - bazel
