---
- name: Install Bazel
  npm:
    name: "@bazel/bazelisk"
    global: true
  tags:
  - bazel
- name: Install bazel compilation database
  vars:
    version: 0.4.5
  shell: 'cd /usr/local/bin && curl -L "https://github.com/grailbio/bazel-compilation-database/archive/{{ version }}.tar.gz" | tar -xz && ln -f -s "/usr/local/bin/bazel-compilation-database-{{ version }}/generate.sh" bazel-compdb'
  become: true
  tags:
  - bazel
- name: Install buildifier
  shell: 'cd /usr/local/bin && curl https://github.com/bazelbuild/buildtools/releases/download/5.0.1/buildifier-linux-amd64 >> /usr/local/bin/buildifier && chmod +x /usr/local/bin/buildifier && ln -s /usr/local/bin/buildifier /usr/bin/buildifier'
