---
- name: Install Bazel
  npm:
    name: "@bazel/bazelisk"
    global: true
  tags:
    - bazel

- name: Download and install StarPLS
  ansible.builtin.get_url:
    url: https://github.com/withered-magic/starpls/releases/download/v0.1.14/starpls-linux-amd64
    dest: /usr/local/bin/starpls
    mode: "0755"

- name: Ensure Go is installed
  ansible.builtin.apt:
    name: golang-go
    state: present
    update_cache: true

- name: Install buildifier
  ansible.builtin.command: "/usr/bin/go install github.com/bazelbuild/buildtools/buildifier@latest"
  environment:
    GOPATH: "{{ main_user_dir }}/go"
