---
- name: Install stylua
  community.general.cargo:
    name: stylua
  tags:
    - rust
    - lua

- name: Install shellharden
  community.general.cargo:
    name: shellharden
  tags:
    - rust

- name: Install tldr
  community.general.cargo:
    name: tealdeer
  tags:
    - rust

- name: Install tldr
  community.general.cargo:
    name: git-delta
  tags:
    - rust
