---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  when: ansible_os_family == "Debian"

- name: Update and upgrade pacman packages
  community.general.pacman:
    update_cache: true
    upgrade: true
  when: ansible_os_family == "Archlinux"

- name: Debian-specific core tasks
  when: ansible_os_family == "Debian"
  block:
    - name: Install system packages and tools (Debian/Ubuntu)
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - bat
          - build-essential
          - curl
          - gettext
          - fzf
          - git
          - git-lfs
          - git-review
          - gitlint
          - lsd
          - ripgrep
          - neofetch
          - net-tools
          - nvidia-settings
          - software-properties-common
          - stow
          - unzip
          - vlc
          - wget
          - xclip
        state: present
        update_cache: true

    - name: Install i3 and required packages (Ubuntu/Debian)
      ansible.builtin.apt:
        name:
          - i3
          - i3blocks
          - i3status
          - feh
          - rofi
          - picom
          - pipewire-pulse
          - pavucontrol
          - xbacklight
          - flameshot
          - dunst
          - redshift
          - autorandr
          - polybar
          - playerctl
          - gtk2-engines-murrine
          - gtk2-engines-pixbuf
          - xsettingsd
        state: present
        update_cache: true

    - name: Install snap packages (Debian)
      when:
        - ansible_os_family == "Debian"
        - not container_check.stat.exists
      community.general.snap:
        name:
          - spotify
          - btop
          - mdl
          - teams-for-linux
        state: present

- name: Arch-specific core tasks
  when: ansible_os_family == "Archlinux"
  block:
    - name: Install system packages and tools (Arch Linux)
      community.general.pacman:
        name:
          - bat
          - base-devel
          - curl
          - ca-certificates
          - gettext
          - fzf
          - git
          - git-lfs
          - go
          - jq
          - lsd
          - ripgrep
          - fastfetch
          - net-tools
          - nvidia-settings
          - openssh
          - sed
          - stow
          - unzip
          - vlc
          - wget
          - xclip
        state: present

    - name: Install i3 and required packages (Arch Linux)
      when: ansible_os_family == "Archlinux"
      community.general.pacman:
        name:
          - i3-wm
          - i3status
          - i3blocks
          - feh
          - rofi
          - picom
          - pipewire-pulse
          - pavucontrol
          - xorg-xbacklight
          - flameshot
          - dunst
          - redshift
          - autorandr
          - polybar
          - playerctl
          - gtk-engine-murrine
          - gtk-engines
          - xsettingsd
        state: present
        update_cache: true

    - name: Install additional tools (Arch Linux)
      community.general.pacman:
        name:
          - btop
          - markdownlint
          - spotify-launcher
        state: present
        update_cache: true

- name: Update CA certificates trust store
  ansible.builtin.command: update-ca-trust
  changed_when: false

- name: Ensure .local/bin directory exists
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ home }}/.local/bin"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Check if batcat is installed
  ansible.builtin.stat:
    path: "/usr/bin/batcat"
  register: batcat_check

- name: Create symbolic link for batcat to bat
  ansible.builtin.file:
    src: "/usr/bin/batcat"
    dest: "{{ home }}/.local/bin/bat"
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"
    force: true
  when: batcat_check.stat.exists
