- name: Install System Packages
  become: true
  apt:
    name: ["autoconf", "automake", "apt-transport-https", "build-essential", "clang-format", "cmake", "curl",\
      "clangd", "g++", "gcc", "gettext", "git", "global", "htop", "libfreetype6-dev", "libfontconfig1-dev",\
      "libxcb-xfixes0-dev", "libxkbcommon-dev", "libtool", "libtool-bin", "lua5.1", "nload", "nvidia-settings",\
      "pkg-config", "python3-pip", "simplescreenrecorder", "software-properties-common", "stow", "unzip", "wget",\
      "xclip"]
  tags:
    - install
    - neovim
    - core
- name: Install Clang
  become: true
  apt:
    name: ["clang", "clang-11", "clang-12", "clangd", "clangd-10", "clangd-11", "clangd-12"]
  tags:
    - install
    - neovim
    - core
