---
- name: "Checking if discord is installed"
  command: "dpkg-query -W discord"
  register: discord_check_deb
  failed_when: discord_check_deb.rc > 1
  changed_when: discord_check_deb.rc == 1
  tags:
    - discord
- name: Install discord
  become: true
  apt:
    deb: https://discord.com/api/download?platform=linux&format=deb
  when: discord_check_deb.rc == 1
  tags:
    - discord
- name: Launch Discord in background to create config files
  become: true
  become_user: "{{ main_user }}"
  shell: discord &
  tags:
    - discord
- name: Download Better discord
  become: true
  become_user: "{{ main_user }}"
  shell: "cd {{ main_user_dir }}/Downloads && wget https://github.com/BetterDiscord/Installer/releases/latest/download/BetterDiscord-Linux.AppImage"
  tags:
    - discord
- name: Make Better discord an executable
  become: true
  become_user: "{{ main_user }}"
  shell: "chmod +x {{ main_user_dir }}/Downloads/BetterDiscord-Linux.AppImage"
  tags:
    - discord
- name: Launch Better discord installer
  become: true
  become_user: "{{ main_user }}"
  shell: "cd {{ main_user_dir }}/Downloads && ./BetterDiscord-Linux.AppImage &"
  tags:
    - discord
