---
- name: Install dmenu deps
  become: true
  apt:
    update_cache: yes
    name: ["meson", "suckless-tools", "stterm"]
  tags:
  - dwm
  - dmenu
- name: dwm - Clone
  become: yes
  become_user: "{{ main_user }}"
  ansible.builtin.git:
    repo: "https://github.com/bakkeby/dmenu-flexipatch.git"
    dest: "{{ main_user_dir }}/dmenu"
  tags:
  - dwm
  - dmenu
# - name: dwm - config.h
#   copy:
#     src: files/dmenu/config.def.h
#     dest: "{{ main_user_dir }}/dmenu"
#   tags:
#   - dwm
#   - dmenu
- name: dmenu - patches.h
  copy:
    src: files/dmenu/patches.def.h
    dest: "{{ main_user_dir }}/dmenu"
  tags:
  - dwm
  - dmenu
- name: dmenu - Install
  become: true
  shell: "cd {{ main_user_dir }}/dmenu && make install"
  tags:
  - dwm
  - dmenu
