---
- name: Install Stow
  become: true
  apt: name=stow
  tags:
  - stow
  - dotfiles
- name: Clone the dotfiles repo
  become_user: "{{ lookup('env', 'USER' }}"
  ansible.builtin.git:
    repo: 'https://github.com/FBorowiec/dotfiles.git'
    dest: "/home/{{ lookup('env', 'USER') }}/dotfiles"
  tags:
  - stow
  - dotfiles
- name: Stow dotfiles (run ~/dotfiles/install)
  become_user: "{{ lookup('env', 'USER' }}"
  shell: cd /home/{{ lookup('env', 'USER') }}/dotfiles && ./install
  tags:
  - stow
  - dotfiles
