---
- name: Install Stow
  become: true
  apt: name=stow
  tags:
  - stow
  - dotfiles
- name: Clone the .dotfiles repo
  ansible.builtin.git:
    repo: "git@github.com:FBorowiec/dotfiles.git"
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    update: yes
    accept_hostkey: yes
    version: main
  tags:
  - stow
  - dotfiles
- name: Stow dotfiles (run ~/.dotfiles/install)
  shell: cd $HOME/.dotfiles && ./install
  tags:
  - stow
  - dotfiles
