---
- name: Install dwm deps
  become: true
  apt:
    update_cache: yes
    name: ["meson", "suckless-tools", "stterm"]
  tags:
  - dwm
- name: Clone pamixer
  become: yes
  become_user: "{{ main_user }}"
  ansible.builtin.git:
    repo: 'https://github.com/cdemoulins/pamixer.git'
    dest: "{{ main_user_dir }}/pamixer"
  tags:
   - dwm
- name: Build pamixer
  become: yes
  become_user: "{{ main_user }}"
  shell: "cd {{ main_user_dir }}/pamixer && meson setup build"
  tags:
    - dwm
- name: Install pamixer
  shell: "cd {{ main_user_dir }}/pamixer && meson install -C build"
  become: true
  tags:
    - dwm
- name: dwm - Download
  become: yes
  become_user: "{{ main_user }}"
  get_url:
    url: https://dl.suckless.org/dwm/dwm-6.2.tar.gz
    dest: "{{ main_user_dir }}"
  tags:
    - dwm
- name: dwm - Extract
  become: yes
  become_user: "{{ main_user }}"
  ansible.builtin.unarchive:
    src: "{{ main_user_dir }}/dwm-6.2.tar.gz"
    dest: "{{ main_user_dir }}"
  tags:
    - dwm
- name: dwm - config.h
  become: yes
  become_user: "{{ main_user }}"
  copy:
    src: config.h
    dest: "{{ main_user_dir }}/dwm-6.2"
  tags:
    - dwm
- name: dwm - Patch dwm
  become: yes
  become_user: "{{ main_user }}"
  shell: patch "{{ main_user_dir }}/dwm-6.2/dwm.c" files/dwm/*.diff
  tags:
    - dwm
- name: dwm - Install dwm dependencies
  become: true
  apt:
    pkg:
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
  tags:
    - dwm
- name: dwm - Build
  become: yes
  become_user: "{{ main_user }}"
  shell: "cd {{ main_user_dir }}/dwm-6.2 && make"
  tags:
    - dwm
- name: dwm - Install
  become: true
  shell: "cd {{ main_user_dir }}/dwm-6.2 && make install"
  tags:
    - dwm
- name: dwm - dwm.desktop
  become: true
  copy:
    src: dwm.desktop
    dest: /usr/share/xsessions
  tags:
    - dwm
- name: dmw - Cleanup
  become: yes
  become_user: "{{ main_user }}"
  ansible.builtin.file:
    path: "{{ main_user_dir }}/dwm-6.2.tar.gz"
    state: absent
  tags:
    - dwm
