---
- name: Install dwm deps
  become: true
  apt:
    update_cache: yes
    name: ["suckless-tools", "stterm"]
  tags:
  - dwm
- name: dwm - Download
  get_url:
    url: https://dl.suckless.org/dwm/dwm-6.2.tar.gz
    dest: "/home/{{ lookup('env', 'USER') }}"
  tags:
    - dwm
- name: dwm - Extract
  ansible.builtin.unarchive:
    src: "/home/{{ lookup('env', 'USER') }}/dwm-6.2.tar.gz"
    dest: "/home/{{ lookup('env', 'USER') }}"
  tags:
    - dwm
- name: dwm - config.h
  copy:
    src: config.h
    dest: "/home/{{ lookup('env', 'USER') }}/dwm-6.2"
  tags:
    - dwm
- name: dwm - Patch dwm for no border on one maximized window
  shell: patch "/home/{{ lookup('env', 'USER') }}/dwm-6.2/dwm.c" files/noborder.diff
  tags:
    - dwm
- name: dwm - Install dwm dependencies
  become: true
  apt:
    pkg:
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
  tags:
    - dwm
- name: dwm - Build
  shell: "cd /home/{{ lookup('env', 'USER') }}/dwm-6.2 && make"
  tags:
    - dwm
- name: dwm - Install
  become: true
  shell: "cd /home/{{ lookup('env', 'USER') }}/dwm-6.2 && make install"
  tags:
    - dwm
- name: dwm - dwm.desktop
  become: true
  copy:
    src: dwm.desktop
    dest: /usr/share/xsessions
  tags:
    - dwm
- name: dmw - Cleanup
  ansible.builtin.file:
    path: "/home/{{ lookup('env', 'USER') }}/dwm-6.2.tar.gz"
    state: absent
  tags:
    - dwm
