---
- name: Configure Mozilla Firefox repository
  become: true
  apt_repository:
    repo: "ppa:mozillateam/ppa"
    state: present
  tags:
    - firefox

- name: Create apt preferences for Mozilla Firefox
  become: true
  blockinfile:
    path: /etc/apt/preferences.d/mozilla-firefox
    block: |
      Package: *
      Pin: release o=LP-PPA-mozillateam
      Pin-Priority: 1001

      Package: firefox
      Pin: version 1:1snap1-0ubuntu2
      Pin-Priority: -1
  tags:
    - firefox

- name: Remove Mozilla Firefox snap package
  become: true
  shell: snap remove firefox
  ignore_errors: true
  tags:
    - firefox

- name: Install Mozilla Firefox using apt
  become: true
  apt:
    name: firefox
    state: latest
  tags:
    - firefox

- name: Configure unattended-upgrades for Mozilla Firefox repository
  become: true
  blockinfile:
    path: /etc/apt/apt.conf.d/51unattended-upgrades-firefox
    block: |
      Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:{{ ansible_distribution_release }}";
  tags:
    - firefox
