---
- name: X/fonts - Create fonts directory
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.file:
    path: "{{ main_user_dir }}/.local/share/fonts/"
    state: directory
    mode: "0755"
  tags:
    - fonts

- name: X/fonts - Install monaco font
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.copy:
    src: ansible.builtin.files/monaco.ttf
    dest: "{{ main_user_dir }}/.local/share/fonts"
    mode: "0644"
  tags:
    - fonts

- name: Install font - Droid Sans Mono for Powerline Nerd Font Complete
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/DroidSansMNerdFont-Regular.otf
    dest: "{{ main_user_dir }}/.local/share/fonts/Droid_Sans_Mono_for_Powerline_Nerd_Font_Complete.otf"
    mode: "0644"
  tags:
    - fonts

- name: Install font - Hack Regular Nerd Font Complete
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Regular/HackNerdFont-Regular.ttf
    dest: "{{ main_user_dir }}/.local/share/fonts/Hack_Regular_Nerd_Font_Complete.ttf"
    mode: "0644"
  tags:
    - fonts

- name: Install font - MesloLGS NF Regular
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Meslo/S/Regular/MesloLGSNerdFont-Regular.ttf
    dest: "{{ main_user_dir }}/.local/share/fonts/MesloLGS_NF_Regular.ttf"
    mode: "0644"
  tags:
    - fonts

- name: Install font - MesloLGS NF Bold
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
    dest: "{{ main_user_dir }}/.local/share/fonts/MesloLGS_NF_Bold.ttf"
    mode: "0644"
  tags:
    - fonts

- name: Install font - MesloLGS NF Italic
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
    dest: "{{ main_user_dir }}/.local/share/fonts/MesloLGS_NF_Italic.ttf"
    mode: "0644"
  tags:
    - fonts

- name: Install font - MesloLGS NF Bold Italic
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
    dest: "{{ main_user_dir }}/.local/share/fonts/MesloLGS_NF_Bold_Italic.ttf"
    mode: "0644"
  tags:
    - fonts

- name: Install font - Hermit medium mono
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hermit/Regular/HurmitNerdFontMono-Regular.otf
    dest: "{{ main_user_dir }}/.local/share/fonts/Hurmit_Medium_Nerd_Font_Complete_Mono.otf"
    mode: "0644"
  tags:
    - fonts

- name: Install font - Hermit medium
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hermit/Regular/HurmitNerdFont-Regular.otf
    dest: "{{ main_user_dir }}/.local/share/fonts/Hurmit_Medium_Nerd_Font_Complete.otf"
    mode: "0644"
  tags:
    - fonts

- name: Install additional fonts
  become: true
  ansible.builtin.apt:
    name: ["fonts-powerline", "fonts-font-awesome", "fonts-firacode"]
  tags:
    - fonts

- name: Install font - Hermit medium
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/NoLigatures/Regular/JetBrainsMonoNLNerdFont-Regular.ttf
    dest: "{{ main_user_dir }}/.local/share/fonts/Hurmit_Medium_Nerd_Font_Complete.otf"
    mode: "0644"
  tags:
    - fonts

- name: Download fonts zip ansible.builtin.file
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/3270.zip"
    dest: "{{ main_user_dir }}/3270.zip"
    mode: "0644"
  tags:
    - fonts

- name: Unzip fonts
  ansible.builtin.unarchive:
    src: "{{ main_user_dir }}/3270.zip"
    dest: "{{ main_user_dir }}/.local/share/fonts"
    remote_src: true
    extra_opts: --strip-components=1
  tags:
    - fonts

- name: Remove old zip ansible.builtin.file
  ansible.builtin.file:
    path: "{{ main_user_dir }}/3270.zip"
    state: absent
  tags:
    - fonts

- name: X/fonts - Refresh font cache
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.command: fc-cache -fv
  register: refreshed_font_cache
  changed_when: refreshed_font_cache.rc != 0
  failed_when: refreshed_font_cache.rc != 0
  tags:
    - fonts
