---
- name: X/fonts - Create fonts directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/fonts/"
    state: directory
  tags:
  - fonts
- name: X/fonts - Install monaco font
  copy:
    src: files/monaco.ttf
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
  tags:
  - fonts
- name: Install font - Droid Sans Mono for Powerline Nerd Font Complete
  get_url:
    url:  https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/Droid_Sans_Mono_for_Powerline_Nerd_Font_Complete.otf"
  tags:
  - fonts
- name: Install font - Hack Regular Nerd Font Complete
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/Hack_Regular_Nerd_Font_Complete.ttf"
  tags:
  - fonts
- name: Install font - MesloLGS NF Regular
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/MesloLGS_NF_Regular.ttf"
  tags:
  - fonts
- name: Install font - MesloLGS NF Bold
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/MesloLGS_NF_Bold.ttf"
  tags:
  - fonts
- name: Install font - MesloLGS NF Italic
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/MesloLGS_NF_Italic.ttf"
  tags:
  - fonts
- name: Install font - MesloLGS NF Bold Italic
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/MesloLGS_NF_Bold_Italic.ttf"
  tags:
  - fonts
- name: X/fonts - Refresh font cache
  shell: fc-cache -fv
  tags:
  - fonts
- name: Install fonts-powerline
  apt:
    name: fonts-powerline
  become: yes
  tags:
  - fonts
