---
- name: Register the current Go version
  become: true
  stat:
    path: /usr/local/go
  register: go_installation
- name: Download the Go tarball
  become: true
  get_url:
    url: "https://storage.googleapis.com/golang/go1.15.2.linux-amd64.tar.gz"
    dest: "/usr/local/src/go1.15.2.linux-amd64.tar.gz"
    checksum: "sha256:b49fda1ca29a1946d6bb2a5a6982cf07ccd2aba849289508ee0f9918f6bb4552"
  when: not go_installation.stat.exists
- name: Extract the Go tarball
  become: true
  unarchive:
    src: /usr/local/src/go1.15.2.linux-amd64.tar.gz
    dest: /usr/local
    copy: false
  when: not go_installation.stat.exists
