---
- name: Add grub-customizer apt repo
  ansible.builtin.apt_repository:
    repo: "ppa:trebelnik-stefina/grub-customizer"
    state: present
  become: true
  tags:
    - grub

- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  tags:
    - grub

- name: Install grub customizer
  become: true
  ansible.builtin.apt:
    name: ["grub-customizer"]
  tags:
    - grub
