---
- name: Install deps
  become: true
  apt:
    name: ["chrome-gnome-shell", "gnome-shell-extensions", "curl", "unzip"]
  tags:
    - gtk
- name: Create themes directory
  become: true
  become_user: "{{ main_user }}"
  file:
    path: "{{ main_user_dir }}/.themes"
    state: directory
  tags:
    - gtk
- name: Clone Nordic theme
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.git:
    repo: "https://github.com/EliverLara/Nordic.git"
    dest: "{{ main_user_dir }}/.themes/Nordic"
  tags:
    - gtk
- name: Set gtk theme
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.desktop.interface gtk-theme "Nordic"'
  tags:
    - gtk
- name: Set user nordic theme
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.shell.extensions.user-theme name "Nordic"'
  tags:
    - gtk
- name: Set wm theme
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.desktop.wm.preferences theme "Nordic"'
  tags:
    - gtk
- name: Create icons directory
  become: true
  become_user: "{{ main_user }}"
  file:
    path: "{{ main_user_dir }}/.icons"
    state: directory
  tags:
    - gtk
- name: Add papirus icons
  become: true
  apt_repository:
    repo: 'ppa:papirus/papirus'
    state: present
  tags:
    - gtk
- name: Install papirus-icon-theme
  apt:
    name: papirus-icon-theme
  become: true
  tags:
    - gtk
- name: Install papirus-folders
  apt:
    name: papirus-folders
  become: true
  tags:
    - gtk
- name: Set icons
  become: true
  become_user: "{{ main_user }}"
  shell: gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
  tags:
    - gtk
- name: Set nordic icons theme
  become: true
  shell: papirus-folders -C nordic --theme Papirus-Dark && papirus-folders -C nordic --theme Papirus
  tags:
    - gtk
- name: Download Nordzy cursors
  become: true
  become_user: "{{ main_user }}"
  shell: 'cd {{ main_user_dir }}/.icons && curl -L "https://github.com/alvatip/Nordzy-cursors/releases/download/v0.1.0/Nordzy-cursors.tar.gz" | tar -xz'
  tags:
    - gtk
- name: Set Nordzy cursors
  become: true
  become_user: "{{ main_user }}"
  shell: gsettings set org.gnome.desktop.interface cursor-theme "Nordzy-cursors"
  tags:
    - gtk
- name: Unset extended height
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false'
  tags:
    - gtk
- name: Set launcher on the bottom
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM'
  tags:
    - gtk
- name: Resize dash icons
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 48'
  tags:
    - gtk
- name: Launcher transparency settings 1
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.shell.extensions.dash-to-dock transparency-mode FIXED'
  tags:
    - gtk
- name: Launcher transparency settings 2
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.shell.extensions.dash-to-dock background-opacity 0.0'
  tags:
    - gtk
- name: Launcher transparency settings 3
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.shell.extensions.dash-to-dock unity-backlit-items false'
  tags:
    - gtk
- name: Set close button to the left
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.desktop.wm.preferences button-layout close,minimize,maximize:'
  tags:
    - gtk
- name: Download wallpaper
  become: true
  shell: cp files/star_wars_last_supper.jpg /usr/share/backgrounds/star_wars_last_supper.jpg
  tags:
    - gtk
- name: Set wallpaper
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/backgrounds/star_wars_last_supper.jpg"'
  tags:
    - gtk
- name: Disable fixed dock
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false'
  tags:
    - gtk
- name: Autohid launcher
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.shell.extensions.dash-to-dock autohide true'
  tags:
    - gtk
- name: Hide trash icon
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.shell.extensions.dash-to-dock show-trash false'
  tags:
    - gtk
- name: Disable home
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.shell.extensions.ding show-home false'
  tags:
    - gtk
- name: Show seconds in clock
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.desktop.interface clock-show-seconds true'
  tags:
    - gtk
- name: Show calendar week in cal
  become: true
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.desktop.calendar show-weekdate true'
  tags:
    - gtk
- name: Hide mounted disks
  become: true
  become_user: "{{ main_user }}"
  shell: gsettings set org.gnome.nautilus.desktop volumes-visible 'false'
  tags:
    - gtk
