---
- name: Download sur5r keyring package
  command: "/usr/lib/apt/apt-helper download-file https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2023.02.18_all.deb keyring.deb SHA256:a511ac5f10cd811f8a4ca44d665f2fa1add7a9f09bef238cdfad8461f5239cc4"
  args:
    chdir: "{{ ansible_env.HOME }}"
  become_user: "{{ main_user }}"

- name: Install sur5r keyring package
  apt:
    deb: "{{ ansible_env.HOME }}/keyring.deb"
  become: true

- name: Add sur5r repository
  ansible.builtin.shell: |
    echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" | sudo tee /etc/apt/sources.list.d/sur5r-i3.list
  become: true

- name: Update apt cache
  apt:
    update_cache: true
  become: true

- name: Install i3 window manager
  apt:
    name: i3
    state: present
  become: true
