---
- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  tags:
    - ergodox

- name: Install Libusb
  become: true
  ansible.builtin.apt:
    name:
      - libusb-1.0-0-dev
  tags:
    - ergodox

- name: Udev rule
  become: true
  ansible.builtin.copy:
    src: files/ergodox/50-zsa.rules
    dest: /etc/udev/rules.d/
    mode: "0644"
  tags:
    - ergodox

#   - name: Add plugdev to sudoers
#     become: true
#     shell: 'groupadd plugdev'
#     tags:
#       - ergodox
#   - name: Add user to plugdev group
#     become: true
#     shell: 'usermod -aG plugdev {{ main_user }}'
#     tags:
#       - ergodox
#
- name: Download wally
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.get_url:
    url: https://configure.ergodox-ez.com/wally/linux
    dest: "{{ main_user_dir }}/Downloads"
    mode: "0644"
  tags:
    - ergodox

- name: Make wally executable
  become: true
  ansible.builtin.file:
    dest: "{{ main_user_dir }}/Downloads/wally"
    mode: a+x
  tags:
    - ergodox
