---
- name: Clone Neovim
  become: true
  become_user: "{{ main_user }}"
  retries: 3
  delay: 10
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ main_user_dir }}/neovim"
    version: master
  tags:
    - neovim

- name: Install build requirements for neovim
  become: true
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
      - luarocks
    update_cache: true
  tags:
    - neovim

- name: Neovim Plugin Development luacheck
  ansible.builtin.command: luarocks install luacheck
  register: luacheck_install
  changed_when: luacheck_install.rc != 0
  failed_when: luacheck_install.rc != 0
  retries: 3
  delay: 10
  ignore_errors: true
  tags:
    - neovim

- name: Build neovim
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.shell: "cd {{ main_user_dir }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"
  register: build_neovim
  changed_when: build_neovim.rc != 0
  failed_when: build_neovim.rc != 0
  tags:
    - neovim

- name: Install neovim
  become: true
  ansible.builtin.shell: "cd {{ main_user_dir }}/neovim && make install"
  register: install_neovim
  changed_when: install_neovim.rc != 0
  failed_when: install_neovim.rc != 0
  tags:
    - neovim
