---
- name: Clone Neovim
  become: true
  become_user: "{{ main_user }}"
  retries: 3
  delay: 10
  ignore_errors: true
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ main_user_dir }}/neovim"
  tags:
    - neovim
- name: Checkout stable branch
  become: true
  become_user: "{{ main_user }}"
  shell: "cd {{ main_user_dir }}/neovim && git checkout nightly"
  tags:
    - neovim
- name: Install build requirements for neovim
  become: true
  apt:
    pkg:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: latest
    update_cache: true
  tags:
    - nvim
- name: Neovim Plugin Development 1
  apt: name=luarocks
  become: true
  tags:
    - neovim
- name: Neovim Plugin Development 2 luacheck
  shell: luarocks install luacheck
  retries: 3
  delay: 10
  ignore_errors: true
  tags:
    - neovim
# - name: Neovim Plugin Development 3 luaformatter
#   shell: luarocks install --server=https://luarocks.org/dev luaformatter
#   tag:
#     - neovim
- name: Build neovim
  become: true
  become_user: "{{ main_user }}"
  shell: "cd {{ main_user_dir }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"
  tags:
    - neovim
- name: Install neovim
  shell: "cd {{ main_user_dir }}/neovim && make install"
  become: true
  tags:
    - neovim
- name: Install Vim-Plug
  become: true
  become_user: "{{ main_user }}"
  shell: "curl -fLo {{ main_user_dir }}/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  tags:
    - neovim
