---
- name: Clone Neovim
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "/home/{{ lookup('env', 'USER') }}/neovim"
  tags:
    - neovim
- name: Checkout stable branch
  shell: "cd /home/{{ lookup('env', 'USER') }}/neovim && git checkout release-0.6"
  tags:
    - neovim
- name: Install build requirements for neovim
  become: true
  apt:
    pkg:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: latest
    update_cache: true
  tags:
    - nvim
- name: Neovim Plugin Development 1
  apt: name=luarocks
  become: true
  tags:
    - neovim
- name: Neovim Plugin Development 2 luacheck
  shell: luarocks install luacheck
  tags:
    - neovim
- name: Build neovim
  shell: "cd /home/{{ lookup('env', 'USER') }}/neovim && make"
  tags:
    - neovim
- name: Install neovim
  shell: "cd /home/{{ lookup('env', 'USER') }}/neovim && make install"
  become: true
  tags:
    - neovim
- name: Install Vim-Plug
  shell: curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  tags:
    - neovim
