- name: Install nodejs and npm
  become: true
  apt:
    name: ['nodejs', 'npm']
  tags:
  - install
  - node
- name: Install yarn
  apt_key:
    id: 1646B01B86E50310
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
  tags:
    - install
    - node
