---
- name: Install Yarn
  npm:
    name: yarn
    global: yes
  tags:
  - node
- name: Install eslint
  npm:
    name: eslint
    global: yes
  tags:
  - node
- name: Install Typescript server
  npm:
    name: typescript-language-server
    global: yes
  tags:
  - node
- name: Install Typescript
  npm:
    name: typescript
    global: yes
  tags:
  - node
- name: Install TS-Node
  npm:
    name: ts-node
    global: yes
  tags:
  - node
- name: Install bash lsp
  npm:
    name: bash-language-server
    global: yes
  tags:
  - node
- name: Install lua formatter
  npm:
    name: lua-fmt
    global: yes
  tags:
  - node
- name: Install jsonlint
  npm:
    name: jsonlint
    global: yes
  tags:
  - node
- name: Install fixjson
  npm:
    name: fixjson
    global: yes
  tags:
  - node
- name: Install markdownlint
  npm:
    name: markdownlint
    global: yes
  tags:
  - node
- name: Install PG format
  npm:
    name: pg-format
    global: yes
  tags:
  - node
- name: Install emojione
  npm:
    name: emojione
    global: yes
  tags:
  - node
