---
- name: Install npm packages
  npm:
    name: "{{ item }}"
    global: true
  loop:
    - yarn
    - eslint
    - typescript-language-server
    - typescript
    - ts-node
    - bash-language-server
    - lua-fmt
    - jsonlint
    - fixjson
    - markdownlint
    - pg-format
    - emojione
    - live-server
    - neovim
    - "@githubnext/github-copilot-cli"
  tags:
    - node
