---
- name: Install obsidian
  apt:
    deb: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.0.3/obsidian_1.0.3_amd64.deb
  when: obsidian_package_check is failed and ansible_facts['os_family'] == "Debian"
  tags:
    - obsidian
- name: "Check if obsidian vault exists"
  stat:
    path: "{{ main_user_dir }}/zettelkasten"
  register: obsidian_vault
  tags:
    - obsidian
- name: Clone obsidian vault repo
  become: true
  become_user: "{{ main_user }}"
  shell: "git clone git@github.com:fborowiec/zettelkasten.git {{ main_user_dir }}/zettelkasten"
  when: not obsidian_vault.stat.exists
  tags:
    - obsidian
