- name: Install python lsp server
  pip:
    name: 'python-lsp-server[all]'
    executable: pip3
- name: Install lookatme with extensions
  pip:
    name: ["lookatme", "lookatme.contrib.qrcode", "lookatme.contrib.image-ueberzug", "lookatme.contrib.render"]

