---
- name: Install python lsp server
  ansible.builtin.pip:
    name: "python-lsp-server[all]"
    executable: pip3
  tags:
    - python

- name: Install lookatme
  ansible.builtin.pip:
    name: ["lookatme"]
    executable: pip3
  tags:
    - python

- name: Install lookatme extensions
  ansible.builtin.pip:
    name: ["lookatme.contrib.image_ueberzug", "lookatme.contrib.render"]
    executable: pip3
  ignore_errors: true
  tags:
    - python

- name: Install zsh deps
  ansible.builtin.pip:
    name: ["poppler-utils", "thefuck"]
    executable: pip3
  tags:
    - python

- name: Neovim deps part 1
  ansible.builtin.pip:
    name: ["pynvim", "pylint", "pycodestyle", "pydocstyle", "jedi", "mypy"]
    executable: pip3
  tags:
    - python

- name: Neovim deps part 2
  ansible.builtin.pip:
    name: ["pylsp-mypy", "black", "python-lsp-black", "flake8", "pyls-flake8"]
    executable: pip3
  tags:
    - python

- name: Neovim deps part 3
  ansible.builtin.pip:
    name: ["isort", "pyls-isort", "rope", "pylsp-rope"]
    executable: pip3
  tags:
    - python

- name: C++ deps
  ansible.builtin.pip:
    name: ["cmakelang"]
    executable: pip3
  tags:
    - python
    - cpp

- name: SQL deps
  ansible.builtin.pip:
    name: ["sqlfluff"]
    executable: pip3
  tags:
    - python
    - sql

- name: Libs I use a lot
  ansible.builtin.pip:
    name:
      - "pydantic"
      - "tenacity"
      - "pandas"
      - "numpy"
      - "pylint-pydantic"
      - "pylint"
    executable: pip3
  tags:
    - python

- name: OpenAI
  ansible.builtin.pip:
    name: ["click", "openai"]
    executable: pip3
  tags:
    - python
