---
- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  tags:
    - postgres

- name: Install postgres
  become: true
  ansible.builtin.apt:
    name: ["postgresql", "postgresql-contrib"]
  tags:
    - postgres

- name: Start postgres service
  become: true
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true
  tags:
    - postgres
