---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: true
    update_cache: true
  tags:
    - postgres
- name: Install postgres
  become: true
  apt:
    name: ["postgres", "postgresql-contrib"]
  tags:
    - postgres
- name: Start postgres service
  become: true
  shell: 'systemctl start postgresql.service'
  tags:
    - postgres
