---
- name: Check if Cargo is installed
  ansible.builtin.command: cargo --version
  register: cargo_installed
  ignore_errors: true
  changed_when: false

- name: Download and install Rust and Cargo
  ansible.builtin.shell: |
    set -o pipefail
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source $HOME/.cargo/env
  when: cargo_installed is failed
  changed_when: false
  tags:
    - rust
    - cargo
