---
- name: Install mdl
  ansible.builtin.command: snap install mdl
  register: snap_install
  changed_when: snap_install.rc != 0
  failed_when: snap_install.rc != 0
  become: true
  tags:
    - snap
