---
- name: Install mdl
  ansible.builtin.command: snap install mdl
  register: snap_install
  changed_when: snap_install.rc != 0
  failed_when: snap_install.rc != 0
  become: true
  tags:
    - snap
- name: Install alacritty
  ansible.builtin.command: snap install alacritty --classic
  register: alacritty_install
  changed_when: alacritty_install.rc != 0
  failed_when: alacritty_install.rc != 0
  become: true
  tags:
    - snap
- name: Install shfmt
  ansible.builtin.command: snap install shfmt
  register: shfmt_install
  changed_when: shfmt_install.rc != 0
  failed_when: shfmt_install.rc != 0
  become: true
  tags:
    - snap
