---
- name: Connect to spotify keyserver
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present
    id: BBEBDCB318AD50EC6865090613B00F1FD2C19886
  tags:
  - spotify
- name: Set ppa spotify
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    update_cache: yes
  tags:
  - spotify
- name: Install spotify
  become: true
  become_user: root
  apt:
    name: spotify-client
    state: present
  tags:
  - spotify
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  tags:
  - spotify
