---
- name: Download spotify apt keys
  shell: curl -sS https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg | apt-key add -
  become: true
  tags:
  - spotify
- name: Add spotify to sources list
  shell: echo "deb http://repository.spotify.com stable non-free" | tee /etc/apt/sources.list.d/spotify.list
  become: true
  tags:
  - spotify
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  tags:
  - spotify
- name: Install Spotify
  become: true
  apt:
    name: ["spotify-client"]
  tags:
  - spotify
