- name: Add Spotify repo key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 4773BD5E130D1D45
    state: present
  become: yes
  register: repo_key_added
  tags:
    - install
    - spotify
- name: Add sources to spotify.list
  lineinfile:
    dest: /etc/apt/sources.list.d/spotify.list
    line: "deb http://repository.spotify.com stable non-free"
    create: yes
  become: yes
  register: sources_added
  when: repo_key_added|succeeded and ansible_distribution == 'Ubuntu'
  tags:
    - install
    - spotify
- name: Install spotify-client
  apt:
    name: spotify-client
    update_cache: yes
    force: yes
  become: yes
  when: sources_added|succeeded
  tags:
    - install
    - spotify
