---
- name: Ensure .ssh directory exists.
  become_user: "{{ lookup('env', 'USER' }}"
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
  - ssh
- name: Install ssh key
  become_user: "{{ lookup('env', 'USER' }}"
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
  - ssh
- name: Install ssh key public
  become_user: "{{ lookup('env', 'USER' }}"
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
  - ssh
