---
- name: Configure gnome for Debian
  when: ansible_os_family == "Debian"
  block:
    - name: Install dependencies (Ubuntu/Debian)
      become: true
      ansible.builtin.apt:
        name:
          - gnome-shell
          - gnome-shell-extension-prefs
          - gnome-shell-extensions
          - gnome-shell-extension-manager
          - gnome-tweaks
          - gnome-browser-connector
          - gtk2-engines-murrine
        state: present
        update_cache: true

    - name: Install GNOME extensions
      ansible.builtin.include_tasks: tasks/theme/gnome_extensions.yml
      loop: "{{ gnome_extensions }}"
      loop_control:
        label: "Extension {{ item }}"
      vars:
        extension_id: "{{ item }}"
        shell_version: "{{ gnome_shell_version.stdout }}"
        display: ":0"
        dbus_address: "{{ dbus_session_bus_address | default('') }}"
