---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - wget
    - curl
    - jq
    - sed
    - gnome-shell
    - gnome-shell-extension-prefs
    - gnome-shell-extensions
    - gnome-shell-extension-manager
    - gnome-tweaks
    - gnome-browser-connector
    - gtk2-engines-murrine

- name: Get GNOME Shell version
  ansible.builtin.shell: "gnome-shell --version | awk '{print $3}' | cut -d '.' -f 1,2"
  register: gnome_shell_version
  changed_when: false
  become_user: "{{ main_user }}"

- name: Install GNOME extensions
  ansible.builtin.include_tasks: tasks/theme/gnome_extensions.yml
  loop: "{{ gnome_extensions }}"
  loop_control:
    label: "{{ item }}"
  vars:
    extension_id: "{{ item }}"
    shell_version: "{{ gnome_shell_version.stdout }}"
    display: "{{ display }}"
    dbus_address: "{{ dbus_address }}"
