---
- name: Install GNOME extension {{ extension_id }}
  block:
    - name: Fetch extension info
      ansible.builtin.uri:
        url: "https://extensions.gnome.org/extension-info/?pk={{ extension_id }}&shell_version={{ gnome_shell_version.stdout }}"
        return_content: true
      register: ext_info
      failed_when: ext_info.status == 404
      become_user: "{{ main_user }}"

    - name: Parse extension info
      ansible.builtin.set_fact:
        extension_name: "{{ (ext_info.content | from_json).name }}"
        download_url: "https://extensions.gnome.org{{ (ext_info.content | from_json).download_url }}"
        ext_uuid: "{{ (ext_info.content | from_json).uuid }}"
      become_user: "{{ main_user }}"

    - name: Download extension
      ansible.builtin.get_url:
        url: "{{ download_url }}"
        dest: "/tmp/{{ extension_name }}.zip"
      become_user: "{{ main_user }}"

    - name: Install extension
      ansible.builtin.shell: "gnome-extensions install /tmp/{{ extension_name }}.zip -f"
      environment:
        DISPLAY: "{{ lookup('env', 'DISPLAY') | default(':0') }}"
        DBUS_SESSION_BUS_ADDRESS: "{{ lookup('env', 'DBUS_SESSION_BUS_ADDRESS') | default('unix:path=/run/user/{{ ansible_user_uid }}/bus') }}"
      become_user: "{{ main_user }}"

    - name: Remove extension archive
      ansible.builtin.file:
        path: "/tmp/{{ extension_name }}.zip"
        state: absent
      become_user: "{{ main_user }}"

    - name: Enable extension
      ansible.builtin.shell: "gnome-extensions enable {{ ext_uuid }}"
      environment:
        DISPLAY: "{{ lookup('env', 'DISPLAY') | default(':0') }}"
        DBUS_SESSION_BUS_ADDRESS: "{{ lookup('env', 'DBUS_SESSION_BUS_ADDRESS') | default('unix:path=/run/user/{{ ansible_user_uid }}/bus') }}"
      become_user: "{{ main_user }}"
  rescue:
    - name: Report error for extension {{ extension_id }}
      debug:
        msg: "Failed to fetch or install extension with ID {{ extension_id }}"
