---
- name: Unset extended height
  become_user: "{{ main_user }}"
  ansible.builtin.command: "gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false"
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_id }}/bus"

- name: Set launcher on the bottom
  become_user: "{{ main_user }}"
  ansible.builtin.command: "gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM" # LEFT, RIGHT, BOTTOM, TOP
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_id }}/bus"

- name: Resize dash icons
  become_user: "{{ main_user }}"
  ansible.builtin.command: "gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 40" # icons size
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_id }}/bus"

- name: Launcher transparency settings
  become_user: "{{ main_user }}"
  ansible.builtin.command: |
    gsettings set org.gnome.shell.extensions.dash-to-dock transparency-mode FIXED &&
    gsettings set org.gnome.shell.extensions.dash-to-dock background-opacity 1.0 &&
    gsettings set org.gnome.shell.extensions.dash-to-dock unity-backlit-items false
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_id }}/bus"

- name: Set close button to the left
  become_user: "{{ main_user }}"
  ansible.builtin.command: "gsettings set org.gnome.desktop.wm.preferences button-layout close,minimize,maximize:"
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_id }}/bus"

- name: Copy wallpaper
  ansible.builtin.command: cp files/star_wars_last_supper.jpg /usr/share/backgrounds/star_wars_last_supper.jpg
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_id }}/bus"

- name: Set wallpaper
  become_user: "{{ main_user }}"
  ansible.builtin.command: 'gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/backgrounds/star_wars_last_supper.jpg"'
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_id }}/bus"

- name: Disable fixed dock
  become_user: "{{ main_user }}"
  ansible.builtin.command: "gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false" # enable dock overlay
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_id }}/bus"

- name: Autohide launcher
  become_user: "{{ main_user }}"
  ansible.builtin.command: "gsettings set org.gnome.shell.extensions.dash-to-dock autohide true" # autohide
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_id }}/bus"

- name: Autohide launcher
  become_user: "{{ main_user }}"
  ansible.builtin.command: "gsettings set org.gnome.shell.extensions.dash-to-dock background-opacity 0" # 0-1
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_id }}/bus"

- name: Hide trash icon
  become_user: "{{ main_user }}"
  ansible.builtin.command: "gsettings set org.gnome.shell.extensions.dash-to-dock show-trash false"
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_id }}/bus"

- name: Disable home
  become_user: "{{ main_user }}"
  ansible.builtin.command: "gsettings set org.gnome.shell.extensions.ding show-home false"
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_id }}/bus"

- name: Show seconds in clock
  become_user: "{{ main_user }}"
  ansible.builtin.command: "gsettings set org.gnome.desktop.interface clock-show-seconds true"
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_id }}/bus"

- name: Show calendar week in cal
  become_user: "{{ main_user }}"
  ansible.builtin.command: "gsettings set org.gnome.desktop.calendar show-weekdate true"
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_id }}/bus"

- name: Hide mounted disks
  become_user: "{{ main_user }}"
  ansible.builtin.command: "gsettings set org.gnome.nautilus.desktop volumes-visible 'false'"
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_id }}/bus"
