---
- name: Clone the Tokyonight-GTK-Theme repository
  become: true
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: https://github.com/Fausto-Korpsvart/Tokyonight-GTK-Theme.git
    dest: "/tmp/Tokyonight-GTK-Theme"
    update: true
    depth: 1
    force: true
    version: master

- name: Ensure gtk-4.0 config directory exists
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ home }}/.config/gtk-4.0"
    state: directory
    mode: "0755"

- name: Ensure gtk-4.0 assets directory exists
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ home }}/.config/gtk-4.0/assets"
    state: directory
    mode: "0755"

- name: Copy gtk-4.0 css configs
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: "/tmp/Tokyonight-GTK-Theme/themes/src/main/gtk-4.0/"
    dest: "{{ home }}/.config/gtk-4.0/"
    remote_src: true
    mode: preserve

- name: Copy gtk-4.0 assets
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: "/tmp/Tokyonight-GTK-Theme/themes/src/assets/gtk/assets/"
    dest: "{{ home }}/.config/gtk-4.0/assets/"
    remote_src: true
    mode: preserve

- name: Ensure the ~/.icons directory exists
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ home }}/.icons"
    state: directory
    mode: "0755"

- name: Copy Tokyonight-Dark icons to ~/.icons
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: "/tmp/Tokyonight-GTK-Theme/icons/Tokyonight-Dark"
    dest: "{{ home }}/.icons/"
    remote_src: true
    mode: preserve

- name: Check if theme is already installed
  become: true
  become_user: "{{ user }}"
  ansible.builtin.stat:
    path: "{{ home }}/.themes/Tokyonight-Dark"
  register: theme_installed

- name: Run the installer script
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command: "./themes/install.sh"
  args:
    chdir: "/tmp/Tokyonight-GTK-Theme"
  when: not theme_installed.stat.exists
  changed_when: true

- name: Copy custom settings
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: files/gtk/settings.ini
    dest: "{{ home }}/.config/gtk-4.0/settings.ini"
    mode: "0644"

- name: Configure gtk themes
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command: |
    gsettings set {{ item.schema }} {{ item.key }} '{{ item.value }}'
  loop:
    - schema: "org.gnome.shell.extensions.user-theme"
      key: "name"
      value: "Tokyonight-Dark"
    - schema: "org.gnome.desktop.interface"
      key: "icon-theme"
      value: "Tokyonight-Dark"
    - schema: "org.gnome.desktop.interface"
      key: "gtk-theme"
      value: "Tokyonight-Dark"
  environment:
    DISPLAY: "{{ display | default(':0') }}"
    DBUS_SESSION_BUS_ADDRESS: "{{ dbus_address | default('') }}"
  changed_when: false
  failed_when: false
