---
- name: Install i3 and required packages (Ubuntu/Debian)
  ansible.builtin.apt:
    name:
      - i3
      - i3status
      - feh
      - rofi
      - picom
      - pulseaudio
      - pavucontrol
      - xbacklight
      - flameshot
      - dunst
      - redshift
      - autorandr
      - polybar
      - playerctl
      - gtk2-engines-murrine
      - gtk2-engines-pixbuf
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install i3 and required packages (Arch Linux)
  community.general.pacman:
    name:
      - i3-wm
      - i3status
      - feh
      - rofi
      - picom
      - pulseaudio
      - pavucontrol
      - xorg-xbacklight
      - flameshot
      - dunst
      - redshift
      - autorandr
      - polybar
      - playerctl
      - gtk-engine-murrine
      - gtk-engines
    state: present
    update_cache: true
  when: ansible_os_family == "Archlinux"
