---
- name: Install i3 and required packages
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - i3
    - feh
    - rofi
    - picom
    - gtk2-engines-murrine
    - gtk2-engines-pixbuf
#- name: Install Tokyo Night GTK theme
#  ansible.builtin.git:
#    repo: "https://github.com/enkia/tokyo-night-gtk-theme.git"
#    dest: "/tmp/tokyo-night-gtk-theme"
#    depth: 1
#
#- name: Copy GTK theme to /usr/share/themes
#  ansible.builtin.copy:
#    src: "/tmp/tokyo-night-gtk-theme/themes/TokyoNight"
#    dest: "/usr/share/themes/TokyoNight"
#    owner: root
#    group: root
#    mode: "0755"
#
#- name: Ensure GTK config directory exists
#  ansible.builtin.file:
#    path: "{{ home_dir }}/.config/gtk-3.0"
#    state: directory
#    owner: "{{ main_user }}"
#    group: "{{ main_user }}"
#    mode: "0755"
#  become_user: "{{ main_user }}"
#
#- name: Set GTK theme for user
#  ansible.builtin.lineinfile:
#    path: "{{ home_dir }}/.config/gtk-3.0/settings.ini"
#    create: true
#    line: "gtk-theme-name=TokyoNight"
#    owner: "{{ main_user }}"
#    group: "{{ main_user }}"
#  become_user: "{{ main_user }}"
#
#- name: Install Tokyo Night wallpaper
#  become_user: "{{ main_user }}"
#  ansible.builtin.get_url:
#    url: "https://raw.githubusercontent.com/enkia/tokyo-night-vscode-theme/master/logo.png"
#    dest: "{{ home_dir }}/Pictures/tokyo-night-wallpaper.png"
#    mode: "0644"
