---
- name: Install i3 and required packages (Ubuntu/Debian)
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name:
      - i3
      - i3blocks
      - i3status
      - feh
      - rofi
      - picom
      - pipewire-pulse
      - pavucontrol
      - xbacklight
      - flameshot
      - dunst
      - redshift
      - autorandr
      - polybar
      - playerctl
      - gtk2-engines-murrine
      - gtk2-engines-pixbuf
      - xsettingsd
    state: present
    update_cache: true

- name: Install betterlockscreen
  when: ansible_os_family == "Debian"
  block:
    - name: Download betterlockscreen install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/betterlockscreen/betterlockscreen/main/install.sh
        dest: /tmp/betterlockscreen-install.sh
        mode: "0755"

    - name: Install betterlockscreen
      ansible.builtin.command: /tmp/betterlockscreen-install.sh system
      args:
        creates: /usr/local/bin/betterlockscreen

    - name: Clean up install script
      ansible.builtin.file:
        path: /tmp/betterlockscreen-install.sh
        state: absent

- name: Install i3 and required packages (Arch Linux)
  when: ansible_os_family == "Archlinux"
  community.general.pacman:
    name:
      - i3-wm
      - i3status
      - i3blocks
      - feh
      - rofi
      - picom
      - pipewire-pulse
      - pavucontrol
      - xorg-xbacklight
      - flameshot
      - dunst
      - redshift
      - autorandr
      - polybar
      - playerctl
      - gtk-engine-murrine
      - gtk-engines
      - xsettingsd
    state: present
    update_cache: true
