---
- name: Remove Spotify snap package if installed
  ansible.builtin.snap:
    name: spotify
    state: absent

- name: Add Spotify GPG key
  ansible.builtin.apt_key:
    url: https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg
    state: present

- name: Add Spotify repository
  ansible.builtin.apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install spotify-client
  ansible.builtin.apt:
    name: spotify-client
    state: present

- name: Change permissions on /usr/share/spotify
  ansible.builtin.file:
    path: /usr/share/spotify
    mode: "a+rwX"
    recurse: false

- name: Change permissions on /usr/share/spotify/Apps recursively
  ansible.builtin.file:
    path: /usr/share/spotify/Apps
    mode: "a+rwX"
    recurse: true

- name: Run Spotify
  become_user: "{{ main_user }}"
  ansible.builtin.shell:
    cmd: "spotify &"

- name: Allow time for Spotify to create default dir
  ansible.builtin.pause:
    seconds: 5

- name: Install spicetify-cli
  become_user: "{{ main_user }}"
  ansible.builtin.shell: curl -fsSL https://raw.githubusercontent.com/spicetify/cli/main/install.sh | sh -s

- name: Symbolic link for spicetify
  ansible.builtin.file:
    src: "{{ home_dir }}/.spicetify/spicetify"
    dest: "/usr/local/bin/spicetify"
    state: link

- name: Clone Spotify Tokyo Night Theme
  become_user: "{{ main_user }}"
  ansible.builtin.git:
    repo: https://github.com/Gspr-bit/Spotify-Tokyo-Night-Theme.git
    dest: "{{home_dir }}/dev/Spotify-Tokyo-Night-Theme"
    update: false

- name: Create Tokyo theme directory
  become_user: "{{ main_user }}"
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/spicetify/Themes/Tokyo"
    state: directory
    mode: "0755"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"

- name: Copy theme files
  become_user: "{{ main_user }}"
  ansible.builtin.copy:
    src: "{{ home_dir }}/dev/Spotify-Tokyo-Night-Theme/{{ item }}"
    dest: "{{ home_dir }}/.config/spicetify/Themes/Tokyo/{{ item }}"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: "0644"
  with_items:
    - color.ini
    - user.css

- name: Configure spicetify current_theme
  become_user: "{{ main_user }}"
  command: /usr/local/bin/spicetify config current_theme Tokyo

- name: Configure spicetify color_scheme
  become_user: "{{ main_user }}"
  command: /usr/local/bin/spicetify config color_scheme Night

- name: Apply spicetify
  become_user: "{{ main_user }}"
  command: /usr/local/bin/spicetify apply
