---
- name: Create themes directory
  become_user: "{{ main_user }}"
  file:
    path: "{{ home_dir }}/.themes"
    state: directory

- name: Clone Nordic theme
  become_user: "{{ main_user }}"
  ansible.builtin.git:
    repo: "https://github.com/EliverLara/Nordic.git"
    dest: "{{ home_dir }}/.themes/Nordic"
    depth: 1

- name: Set gtk theme
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.desktop.interface gtk-theme "Nordic"'

- name: Set user nordic theme
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.shell.extensions.user-theme name "Nordic"'

- name: Set wm theme
  become_user: "{{ main_user }}"
  shell: 'gsettings set org.gnome.desktop.wm.preferences theme "Nordic"'

- name: Create icons directory
  become_user: "{{ main_user }}"
  file:
    path: "{{ home_dir }}/.icons"
    state: directory

- name: Add papirus icons
  apt_repository:
    repo: "ppa:papirus/papirus"
    state: present

- name: Install papirus themes
  apt:
    name: ["papirus-icon-theme", "papirus-folders"]

- name: Set icons
  become_user: "{{ main_user }}"
  shell: gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"

- name: Set nordic icons theme
  shell: papirus-folders -C nordic --theme Papirus-Dark && papirus-folders -C nordic --theme Papirus

- name: Download Nordzy cursors
  become_user: "{{ main_user }}"
  shell: 'cd {{ home_dir }}/.icons && curl -L "https://github.com/alvatip/Nordzy-cursors/releases/download/v0.1.0/Nordzy-cursors.tar.gz" | tar -xz'

- name: Set Nordzy cursors
  become_user: "{{ main_user }}"
  shell: gsettings set org.gnome.desktop.interface cursor-theme "Nordzy-cursors"
