---
- name: Install Brave Browser
  when: not container_check.stat.exists
  community.general.snap:
    name:
      - brave
    state: present

- name: Run Brave
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    cmd: "brave &"
  when: not container_check.stat.exists
  changed_when: false

- name: Allow time for Brave to create default dir
  ansible.builtin.pause:
    seconds: 5
  when: not container_check.stat.exists

- name: Copy Brave bookmarks
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: "files/brave/Bookmarks"
    dest: "{{ home }}/.config/BraveSoftware/Brave-Browser/Default/Bookmarks"
    mode: "0644"
  when: not container_check.stat.exists
