---
- name: Install Brave Browser
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsS https://dl.brave.com/install.sh | sh
  args:
    creates: /usr/bin/brave-browser
    executable: /bin/bash

- name: Run Brave
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    cmd: "brave &"
  when: not container_check.stat.exists
  changed_when: false

- name: Allow time for Brave to create default dir
  ansible.builtin.pause:
    seconds: 5
  when: not container_check.stat.exists

- name: Copy Brave bookmarks (Debian)
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: "files/brave/Bookmarks"
    dest: "{{ home }}/snap/brave/current/.config/\
      BraveSoftware/Brave-Browser/Default/Bookmarks"
    mode: "0644"
  when:
    - ansible_os_family == "Debian"
    - not container_check.stat.exists

- name: Copy Brave bookmarks (Arch Linux)
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: "files/brave/Bookmarks"
    dest: "{{ home }}/.config/BraveSoftware/Brave-Browser/Default/Bookmarks"
    mode: "0644"
  when:
    - ansible_os_family == "Archlinux"
    - not container_check.stat.exists
