---
- name: Update CA certificates trust store
  ansible.builtin.command: update-ca-trust
  changed_when: false

- name: Ensure .local/bin directory exists
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ home }}/.local/bin"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Check if batcat is installed
  ansible.builtin.stat:
    path: "/usr/bin/batcat"
  register: batcat_check

- name: Create symbolic link for batcat to bat
  ansible.builtin.file:
    src: "/usr/bin/batcat"
    dest: "{{ home }}/.local/bin/bat"
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"
    force: true
  when: batcat_check.stat.exists
