---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  when: ansible_os_family == "Debian"

- name: Debian-specific core tasks
  when: ansible_os_family == "Debian"
  block:
    - name: Install system packages and tools (Debian/Ubuntu)
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - bat
          - build-essential
          - ca-certificates
          - curl
          - gettext
          - fzf
          - git
          - git-lfs
          - git-review
          - gitlint
          - lsd
          - neofetch
          - net-tools
          - nvidia-settings
          - ripgrep
          - software-properties-common
          - stow
          - unzip
          - vlc
          - wget
          - xclip
        state: present
        update_cache: true

    - name: Install i3 and required packages (Ubuntu/Debian)
      ansible.builtin.apt:
        name:
          - autorandr
          - dunst
          - feh
          - flameshot
          - gtk2-engines-murrine
          - gtk2-engines-pixbuf
          - i3
          - i3blocks
          - i3status
          - pavucontrol
          - picom
          - pipewire-pulse
          - redshift
          - rofi
          - playerctl
          - polybar
          - xbacklight
          - xsettingsd
        state: present
        update_cache: true

    - name: Install snap packages (Debian)
      when:
        - ansible_os_family == "Debian"
        - not container_check.stat.exists
      community.general.snap:
        name:
          - btop
          - mdl
          - spotify
          - teams-for-linux
        state: present
