---
- name: Ensure .ssh directory exists
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ home }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Copy keys
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ home }}/.ssh/{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
    - src: "files/ssh/id_ed25519"
      dest: "id_ed25519"
      mode: "0600"
    - src: "files/ssh/id_ed25519.pub"
      dest: "id_ed25519.pub"
      mode: "0644"
    - src: "files/ssh/known_hosts"
      dest: "known_hosts"
      mode: "0644"
