---
- name: Ensure .keys directory exists.
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    dest: "{{ home }}/.keys"
    mode: "0700"
    state: directory

- name: Install anthropic key
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: "files/ai/anthropic_key"
    dest: "{{ home }}/.keys/anthropic_key"
    mode: "0600"

- name: Install Claude
  become: true
  become_user: "{{ user }}"
  community.general.npm:
    name: "@anthropic-ai/claude-code"
    state: present
