---
- name: Install Alacritty
  community.general.cargo:
    name: alacritty
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ main_user }}/.cargo/bin"

- name: Symbolic link for Alacritty
  ansible.builtin.file:
    src: "{{ home_dir }}/.cargo/bin/alacritty"
    dest: "/usr/bin/alacritty"
    state: link

- name: Set Alacritty as the default terminal
  ansible.builtin.command: update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/alacritty 60
  args:
    creates: /usr/bin/x-terminal-emulator

- name: Copy Alacritty icon
  ansible.builtin.copy:
    src: "files/alacritty-simple.svg"
    dest: /usr/share/pixmaps/Alacritty.svg
    mode: "0644"

- name: Create Alacritty desktop entry
  ansible.builtin.shell:
    cmd: desktop-file-install files/Alacritty.desktop && update-desktop-database
