---
- name: Install deps
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - cmake
    - pkg-config
    - libfreetype6-dev
    - libfontconfig1-dev
    - libxcb-xfixes0-dev
    - libxkbcommon-dev

- name: Install Alacritty
  become: true
  become_user: "{{ main_user }}"
  community.general.cargo:
    name: "alacritty"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ home_dir }}/.cargo/bin"

- name: Symbolic link for Alacritty
  ansible.builtin.file:
    src: "{{ home_dir }}/.cargo/bin/alacritty"
    dest: "/usr/bin/alacritty"
    state: link

- name: Set Alacritty as the default terminal
  ansible.builtin.command: >-
    update-alternatives --install /usr/bin/x-terminal-emulator |
    x-terminal-emulator /usr/bin/alacritty 60
  args:
    creates: /usr/bin/x-terminal-emulator

- name: Copy Alacritty icon
  ansible.builtin.copy:
    src: "files/icons/alacritty-simple.svg"
    dest: /usr/share/pixmaps/Alacritty.svg
    mode: "0644"

- name: Install Alacritty desktop file
  ansible.builtin.copy:
    src: files/icons/Alacritty.desktop
    dest: /usr/share/applications/Alacritty.desktop
    mode: "0644"
  notify: update desktop database
