---
- name: Install Barrier and rclone
  ansible.builtin.apt:
    name:
      - barrier
      - rclone
    state: present

- name: Create Barrier SSL Fingerprints directory
  ansible.builtin.file:
    path: "/home/{{ main_user }}/.local/share/barrier/SSL/Fingerprints"
    state: directory
    mode: "0755"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"

- name: Generate Barrier SSL certificate
  become_user: "{{ main_user }}"
  ansible.builtin.command: >
    openssl req -x509 -nodes -days 365 -subj /CN=Barrier
    -newkey rsa:4096
    -keyout /home/{{ main_user }}/.local/share/barrier/SSL/Barrier.pem
    -out /home/{{ main_user }}/.local/share/barrier/SSL/Barrier.pem
  args:
    creates: "/home/{{ main_user }}/.local/share/barrier/SSL/Barrier.pem"

- name: Get SSL certificate fingerprint
  become_user: "{{ main_user }}"
  ansible.builtin.command: >
    openssl x509 -fingerprint -sha256 -noout
    -in /home/{{ main_user }}/.local/share/barrier/SSL/Barrier.pem
  register: fingerprint_output
  args:
    warn: false

- name: Extract fingerprint value
  ansible.builtin.set_fact:
    fingerprint: "{{ fingerprint_output.stdout.split('=')[1] | trim }}"

- name: Write fingerprint to Local.txt
  ansible.builtin.copy:
    content: "v2:sha256:{{ fingerprint }}"
    dest: "{{ home_dir }}/.local/share/barrier/SSL/Fingerprints/Local.txt"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: "0644"
