---
- name: Install Bazel
  npm:
    name: "@bazel/bazelisk"
    global: true

- name: Install buildtools
  ansible.builtin.command: "go install github.com/bazelbuild/buildtools/{{ item }}@latest"
  environment:
    GOPATH: "{{ home_dir }}/go"
    GOBIN: "{{ home_dir }}/go/bin"
    PATH: "/usr/local/go/bin:{{ home_dir }}/go/bin:{{ ansible_env.PATH }}"
  loop:
    - buildifier
    - buildozer
