---
- name: "Checking if Discord is installed"
  ansible.builtin.command: "dpkg-query -W discord"
  register: discord_check_deb
  failed_when: discord_check_deb.rc > 1
  changed_when: discord_check_deb.rc == 1

- name: Install Discord
  become: true
  ansible.builtin.apt:
    deb: https://discord.com/api/download?platform=linux&format=deb
  when: discord_check_deb.rc == 1
