---
- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Check if Docker is already present.
  ansible.builtin.command: which docker
  failed_when: false
  changed_when: false
  check_mode: false
  register: docker_command_result

- name: Download Docker install convenience script.
  ansible.builtin.get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: "0775"
  when: docker_command_result.rc == 1

- name: Run Docker install convenience script.
  ansible.builtin.command: /tmp/get-docker.sh
  environment:
    CHANNEL: stable
  when: docker_command_result.rc == 1

- name: Add user to docker group
  ansible.builtin.command: "usermod -aG docker {{ main_user }}"
- name: Reset connection so docker group is picked up.
  ansible.builtin.meta: reset_connection
