---
- name: Add grub-customizer apt repo
  ansible.builtin.apt_repository:
    repo: "ppa:trebelnik-stefina/grub-customizer"
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install grub customizer
  ansible.builtin.apt:
    name: "grub-customizer"
