---
- name: Ensure software-properties-common is installed (Debian/Ubuntu)
  ansible.builtin.apt:
    name: software-properties-common
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Check if grub-customizer is already installed (Debian/Ubuntu)
  ansible.builtin.command: dpkg -l grub-customizer
  register: grub_customizer_check_deb
  changed_when: false
  failed_when: false
  when: ansible_os_family == "Debian"

- name: Install grub-customizer from PPA (Debian/Ubuntu)
  when:
    - ansible_os_family == "Debian"
    - grub_customizer_check_deb.rc != 0
  block:
    - name: Add grub-customizer PPA
      ansible.builtin.apt_repository:
        repo: "ppa:danielrichter2007/grub-customizer"
        state: present
        update_cache: true

    - name: Install grub-customizer
      ansible.builtin.apt:
        name: grub-customizer
        state: present

    - name: Remove grub-customizer PPA
      ansible.builtin.apt_repository:
        repo: "ppa:danielrichter2007/grub-customizer"
        state: absent
        update_cache: false

- name: Check if grub-customizer is already installed (Arch Linux)
  ansible.builtin.command: pacman -Q grub-customizer
  register: grub_customizer_check_arch
  changed_when: false
  failed_when: false
  when: ansible_os_family == "Archlinux"

- name: Install grub-customizer from source (Arch Linux)
  when:
    - ansible_os_family == "Archlinux"
    - grub_customizer_check_arch.rc != 0
  block:
    - name: Install build dependencies for grub-customizer
      become: true
      community.general.pacman:
        name: [git, cmake, make, gcc, gtkmm3, libarchive, openssl]
        state: present

    - name: Clone and build grub-customizer
      become: true
      ansible.builtin.shell: |
        cd /tmp
        git clone https://git.launchpad.net/grub-customizer
        cd grub-customizer
        cmake . && make && make install
        cd .. && rm -rf grub-customizer
      args:
        creates: /usr/local/bin/grub-customizer
