---
- name: Install libfuse2 dependency
  ansible.builtin.apt:
    name: libfuse2
    state: present
    update_cache: true

- name: Ensure immersed directory exists
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ home }}/immersed"
    state: directory
    mode: "0755"

- name: Ensure .local/share/applications directory exists
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ home }}/.local/share/applications"
    state: directory
    mode: "0755"
    recurse: true

- name: Download Immersed AppImage
  become: true
  become_user: "{{ user }}"
  ansible.builtin.get_url:
    url: "https://static.immersed.com/dl/Immersed-x86_64.AppImage"
    dest: "{{ home }}/immersed/Immersed-x86_64.AppImage"
    mode: "0755"

- name: Copy Immersed icon
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: "files/icons/immersed.png"
    dest: "{{ home }}/immersed/immersed.png"
    mode: "0644"

- name: Create Immersed desktop entry
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    dest: "{{ home }}/.local/share/applications/immersed.desktop"
    mode: "0644"
    content: |
      [Desktop Entry]
      Name=Immersed
      Comment=Virtual workspace for VR
      Exec={{ home }}/immersed/Immersed-x86_64.AppImage
      Icon={{ home }}/immersed/immersed.png
      Terminal=false
      Type=Application
      Categories=Utility;
      StartupWMClass=immersed
  notify: update desktop database
