---
- name: Ensure immersed directory exists
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ home }}/immersed"
    state: directory
    mode: "0755"

- name: Install libfuse2
  ansible.builtin.apt:
    name: libfuse2
    state: present

- name: Download Immersed AppImage
  become_user: "{{ user }}"
  ansible.builtin.get_url:
    url: "https://static.immersed.com/dl/Immersed-x86_64.AppImage"
    dest: "{{ home }}/immersed/Immersed-x86_64.AppImage"
    mode: "0755"

- name: Copy Immersed icon
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: "files/icons/immersed.png"
    dest: "{{ home }}/immersed"
    mode: "0644"

- name: Create Immersed desktop entry
  ansible.builtin.shell:
    cmd: "desktop-file-install --dir={{ home }}/.local/share/applications files/icons/immersed.desktop && update-desktop-database"
