---
- name: K8s for Debian
  when: ansible_os_family == "Debian"
  block:
    - name: Add Kubernetes apt key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        state: present

    - name: Add Kubernetes apt repo
      ansible.builtin.apt_repository:
        repo: "deb https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
        state: present
        filename: kubernetes

    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present
        update_cache: true

    - name: Install helm
      ansible.builtin.apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present
      register: helm_key

    - name: Add helm repo
      ansible.builtin.apt_repository:
        repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
        state: present
        filename: helm-stable-debian

    - name: Install helm package
      ansible.builtin.apt:
        name: helm
        state: present
        update_cache: true

    - name: Download minikube binary
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: "0755"
        force: true

    - name: Download kind binary
      ansible.builtin.get_url:
        url: https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
        dest: /usr/local/bin/kind
        mode: "0755"
        force: true

- name: K8s for Arch
  when: ansible_os_family == "Archlinux"
  community.general.pacman:
    name:
      - helm
      - kind
      - kubectl
      - minikube
    state: present
    update_cache: true
