---
- name: Install additional languages
  become: true
  ansible.builtin.apt:
    name:
      - ruby-full # ruby
      - opam # ocaml
      - latexmk # latex
      - biber # latex
    state: present
    update_cache: true
