---
- name: Install additional languages (Debian/Ubuntu)
  become: true
  ansible.builtin.apt:
    name:
      - ruby-full # ruby
      - opam # ocaml
      - latexmk # latex
      - biber # latex
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install additional languages (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - ruby # ruby
      - opam # ocaml
      - texlive-latexrecommended # latex
      - biber # latex
    state: present
  when: ansible_os_family == "Archlinux"
