---
- name: Install Ranger with deps
  become: true
  ansible.builtin.apt:
    name:
      - ranger
      - caca-utils
      - highlight
      - atool
      - w3m
      - mediainfo
      - lynx
      - ffmpegthumbnailer
      - fzf
      - findutils
      - unzip
    state: present
    update_cache: true
