---
- name: Install Ranger with deps
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - ranger
    - caca-utils
    - highlight
    - atool
    - w3m
    - mediainfo
    - lynx
    - ffmpegthumbnailer
    - fzf
    - findutils
    - unzip
