---
- name: Install Ranger with deps (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - ranger
      - caca-utils
      - highlight
      - atool
      - w3m
      - mediainfo
      - lynx
      - ffmpegthumbnailer
      - fzf
      - findutils
      - unzip
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install Ranger with deps (Arch Linux)
  community.general.pacman:
    name:
      - ranger
      - libcaca
      - highlight
      - atool
      - w3m
      - mediainfo
      - lynx
      - ffmpegthumbnailer
      - fzf
      - findutils
      - unzip
    state: present
  when: ansible_os_family == "Archlinux"
