---
- name: Install snap packages
  ansible.builtin.command: snap install "{{ item }}"
  loop:
    - spotify
    - btop
    - mdl
    - brave
    - teams-for-linux
  register: snap_install
  changed_when: snap_install.rc != 0
  failed_when: snap_install.rc != 0

- name: Paste Brave bookmarks
  ansible.builtin.copy:
    src: "files/brave/Bookmarks"
    dest: "{{ home_dir }}/snap/brave/current/.config/BraveSoftware/Brave-Browser/Default/Bookmarks"
    mode: "0644"
