---
- name: Install spotify
  ansible.builtin.command: snap install spotify
  register: spotify_install
  changed_when: spotify_install.rc != 0
  failed_when: spotify_install.rc != 0

- name: Install btop
  ansible.builtin.command: snap install btop
  register: btop_install
  changed_when: btop_install.rc != 0
  failed_when: btop_install.rc != 0

- name: Install mdl
  ansible.builtin.command: snap install mdl
  register: mdl_install
  changed_when: mdl_install.rc != 0
  failed_when: mdl_install.rc != 0

- name: Install brave
  ansible.builtin.command: snap install brave
  register: brave_install
  changed_when: brave_install.rc != 0
  failed_when: brave_install.rc != 0
