---
- name: Install snapd
  when: ansible_os_family == "Archlinux"
  become: true
  become_user: "{{ user }}"
  kewlfft.aur.aur:
    name: snapd
    state: present

- name: Install snap packages
  community.general.snap:
    name:
      - spotify
      - btop
      - mdl
      - brave
      - teams-for-linux
    state: present
  when: not container_check.stat.exists

- name: Run Brave
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    cmd: "brave &"
  when: not container_check.stat.exists
  changed_when: false

- name: Allow time for Brave to create default dir
  ansible.builtin.pause:
    seconds: 5
  when: not container_check.stat.exists

- name: Copy Brave bookmarks
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: "files/brave/Bookmarks"
    dest: "{{ home }}/snap/brave/current/.config/\
      BraveSoftware/Brave-Browser/Default/Bookmarks"
    mode: "0644"
  when: not container_check.stat.exists
