---
- name: Install snap packages
  ansible.builtin.command: snap install "{{ item }}"
  loop:
    - spotify
    - btop
    - mdl
    - brave
    - teams-for-linux
  register: snap_install
  changed_when: snap_install.rc != 0
  failed_when: snap_install.rc != 0

- name: Run Brave
  become_user: "{{ user }}"
  ansible.builtin.shell:
    cmd: "brave &"

- name: Allow time for Brave to create default dir
  ansible.builtin.pause:
    seconds: 5

- name: Paste Brave bookmarks
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: "files/brave/Bookmarks"
    dest: "{{ home }}/snap/brave/current/.config/BraveSoftware/Brave-Browser/Default/Bookmarks"
    mode: "0644"
