---
- name: Check if NordVPN is already installed
  ansible.builtin.command: which nordvpn
  register: nordvpn_check
  failed_when: false
  changed_when: false

- name: Install nordvpn
  when: nordvpn_check.rc != 0
  block:
    - name: Install nordvpn (Ubuntu/Debian)
      when: ansible_os_family == "Debian"
      block:
        - name: Add NordVPN GPG key
          ansible.builtin.get_url:
            url: https://repo.nordvpn.com/gpg/nordvpn_public.asc
            dest: /etc/apt/trusted.gpg.d/nordvpn.asc
            mode: "0644"

        - name: Add NordVPN repository
          ansible.builtin.apt_repository:
            repo: "deb https://repo.nordvpn.com/deb/nordvpn/debian stable main"
            state: present
            filename: nordvpn

        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: true

        - name: Install NordVPN package
          ansible.builtin.apt:
            name: nordvpn
            state: present
            install_recommends: true

    - name: Install nordvpn (Arch Linux)
      when: ansible_os_family == "Archlinux"
      block:
        - name: Install wireguard-tools (required for NordLynx)
          community.general.pacman:
            name: wireguard-tools
            state: present

        - name: Install build dependencies
          pacman:
            name:
              - libxml2-legacy
            state: present

        - name: Clone nordvpn-bin from AUR
          become: true
          become_user: "{{ user }}"
          ansible.builtin.git:
            repo: https://aur.archlinux.org/nordvpn-bin.git
            dest: /tmp/nordvpn-bin
            depth: 1
            force: true
            version: master

        - name: Build nordvpn-bin package
          become: true
          become_user: "{{ user }}"
          ansible.builtin.shell: |
            cd /tmp/nordvpn-bin
            makepkg --noconfirm
          register: build_result
          args:
            creates: /tmp/nordvpn-bin/pkg/nordvpn-bin

        - name: Find built package file
          ansible.builtin.find:
            paths: /tmp/nordvpn-bin
            patterns: "*.pkg.tar.*"
          register: package_files

        - name: Debug package file
          ansible.builtin.debug:
            msg: "{{ package_files.files[0].path }}"

        - name: Install nordvpn-bin package with pacman
          ansible.builtin.shell: |
            pacman -U "{{ package_files.files[0].path }}" --noconfirm
          args:
            creates: /usr/sbin/nordvpn

- name: Enable nordvpn
  when: nordvpn_check.rc != 0
  block:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Wait for Docker service to be available
      ansible.builtin.wait_for:
        timeout: 10

    - name: Enable and start nordvpnd service
      ansible.builtin.systemd:
        name: nordvpnd
        enabled: true
        state: started
      when: not container_check.stat.exists

    - name: Add user to nordvpn group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: nordvpn
        append: true
