---
- name: Check if NordVPN is already installed
  command: which nordvpn
  register: nordvpn_check
  failed_when: false
  changed_when: false

- name: Install NordVPN on Debian/Ubuntu
  when: ansible_os_family == "Debian" and nordvpn_check.rc != 0
  block:
    - name: Add NordVPN GPG key
      ansible.builtin.get_url:
        url: https://repo.nordvpn.com/gpg/nordvpn_public.asc
        dest: /usr/share/keyrings/nordvpn.asc
        mode: "0644"

    - name: Add NordVPN repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/nordvpn.list
        content: |
          deb [signed-by=/usr/share/keyrings/nordvpn.asc] https://repo.nordvpn.com/deb/nordvpn/debian stable main
        mode: "0644"

    - name: Install NordVPN
      ansible.builtin.apt:
        name: nordvpn
        update_cache: true
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive

- name: Install NordVPN on Arch Linux
  when: ansible_os_family == "Archlinux" and nordvpn_check.rc != 0
  block:
    - name: Install wireguard-tools (required for NordLynx)
      pacman:
        name: wireguard-tools
        state: present

    - name: Install nordvpn-bin from AUR using yay
      become: true
      become_user: "{{ user }}"
      command: yay -S --noconfirm nordvpn-bin
      args:
        creates: /usr/bin/nordvpn

- name: Common NordVPN configuration
  when: nordvpn_check.rc != 0
  block:
    - name: Enable and start nordvpnd service
      systemd:
        name: nordvpnd
        enabled: true
        state: started

    - name: Add user to nordvpn group
      user:
        name: "{{ ansible_user_id }}"
        groups: nordvpn
        append: true
