---
- name: Check if NordVPN is already installed
  ansible.builtin.command: which nordvpn
  register: nordvpn_check
  failed_when: false
  changed_when: false

- name: Install NordVPN on Arch Linux
  when:
    - ansible_os_family == "Archlinux"
    - nordvpn_check.rc != 0
  block:
    - name: Install wireguard-tools (required for NordLynx)
      community.general.pacman:
        name: wireguard-tools
        state: present

    - name: Clone nordvpn-bin AUR repo
      become: true
      become_user: "{{ user }}"
      ansible.builtin.git:
        repo: https://aur.archlinux.org/nordvpn-bin.git
        dest: /tmp/nordvpn-bin
        update: true
        version: master

    - name: Build nordvpn-bin
      become: true
      become_user: "{{ user }}"
      ansible.builtin.command: makepkg -sf --noconfirm
      args:
        chdir: /tmp/nordvpn-bin
        creates: "/tmp/nordvpn-bin/PKGBUILD"

    - name: Install nordvpn-bin package
      become: true
      ansible.builtin.shell: pacman -U --noconfirm /tmp/nordvpn-bin/*.pkg.tar.zst
      args:
        creates: /usr/sbin/nordvpn

- name: Common NordVPN configuration
  when: nordvpn_check.rc != 0
  block:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
      when: docker_check.rc != 0

    - name: Wait for Docker service to be available
      ansible.builtin.wait_for:
        timeout: 10

    - name: Enable and start nordvpnd service
      ansible.builtin.systemd:
        name: nordvpnd
        enabled: true
        state: started
      when: not container_check.stat.exists

    - name: Add user to nordvpn group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: nordvpn
        append: true
