---
- name: Check if NordVPN is already installed
  ansible.builtin.command: which nordvpn
  register: nordvpn_check
  failed_when: false
  changed_when: false

- name: Install nordvpn
  when: nordvpn_check.rc != 0
  block:
    - name: Install nordvpn (Ubuntu/Debian)
      when: ansible_os_family == "Debian"
      block:
        - name: Download NordVPN installer script (Ubuntu/Debian)
          ansible.builtin.get_url:
            url: https://downloads.nordcdn.com/apps/linux/install.sh
            dest: /tmp/nordvpn-install.sh
            mode: "0755"

        - name: Run NordVPN installer script (Ubuntu/Debian)
          become: true
          become_user: "{{ user }}"
          ansible.builtin.command:
            cmd: bash /tmp/nordvpn-install.sh
          args:
            creates: /usr/bin/nordvpn

    - name: Install nordvpn (Arch Linux)
      when: ansible_os_family == "Archlinux"
      block:
        - name: Install wireguard-tools (required for NordLynx)
          community.general.pacman:
            name: wireguard-tools
            state: present

        - name: Install NordVPN via yay
          become: true
          become_user: "{{ user }}"
          ansible.builtin.command:
            cmd: yay -S --noconfirm nordvpn-bin
          args:
            creates: /usr/sbin/nordvpn

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Wait for Docker service to be available
      ansible.builtin.wait_for:
        timeout: 10

    - name: Enable and start nordvpnd service
      ansible.builtin.systemd:
        name: nordvpnd
        enabled: true
        state: started
      when: not container_check.stat.exists

    - name: Add user to nordvpn group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: nordvpn
        append: true
