---
- name: Check if NordVPN is already installed
  ansible.builtin.command: which nordvpn
  register: nordvpn_check
  failed_when: false
  changed_when: false

- name: Install nordvpn
  when: nordvpn_check.rc != 0
  block:
    - name: Install wireguard-tools (required for NordLynx)
      when: ansible_os_family == "Archlinux"
      community.general.pacman:
        name: wireguard-tools
        state: present

    - name: Download and install NordVPN
      become: true
      ansible.builtin.shell: |
        sh <(curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh)
      args:
        creates: /usr/bin/nordvpn

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Wait for Docker service to be available
      ansible.builtin.wait_for:
        timeout: 10

    - name: Enable and start nordvpnd service
      ansible.builtin.systemd:
        name: nordvpnd
        enabled: true
        state: started
      when: not container_check.stat.exists

    - name: Add user to nordvpn group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: nordvpn
        append: true
