---
- name: Install official packages
  when: ansible_os_family == "Archlinux"
  community.general.pacman:
    name:
      - base-devel
      - btop
      - markdownlint
      - spotify-launcher
    state: present
    update_cache: true

- name: Build and install AUR packages
  vars:
    aur_packages:
      # - teams-for-linux # unstable
      - brave-bin
      - grub-customizer
  when: ansible_os_family == "Archlinux"
  block:
    - name: Clone AUR package
      become: true
      become_user: "{{ user }}"
      ansible.builtin.git:
        repo: "https://aur.archlinux.org/{{ item }}.git"
        dest: "/tmp/{{ item }}"
        update: true
        version: master
      loop: "{{ aur_packages }}"

    - name: Check if package is already installed
      ansible.builtin.command:
        cmd: pacman -Q {{ item }}
      register: package_check
      failed_when: false
      changed_when: false
      loop: "{{ aur_packages }}"

    - name: Build AUR package
      become: true
      become_user: "{{ user }}"
      ansible.builtin.command:
        cmd: makepkg -sf --noconfirm --needed
        chdir: "/tmp/{{ item.item }}"
      loop: "{{ package_check.results }}"
      when: item.rc != 0 # Only build if package not installed

    - name: Find built package files
      ansible.builtin.find:
        paths: "/tmp/{{ item.item }}"
        patterns: "*.pkg.tar.*"
      register: built_packages
      loop: "{{ package_check.results }}"
      when: item.rc != 0

    - name: Install built AUR package
      become: true
      ansible.builtin.command:
        cmd: pacman -U --noconfirm {{ item.files[0].path }}
      loop: "{{ built_packages.results }}"
      when:
        - item.files is defined
        - item.files | length > 0

    - name: Clean up AUR build directory
      ansible.builtin.file:
        path: "/tmp/{{ item }}"
        state: absent
      loop: "{{ aur_packages }}"
