---
- name: Install official packages
  when: ansible_os_family == "Archlinux"
  community.general.pacman:
    name:
      - base-devel
      - btop
      - markdownlint
      - spotify-launcher
    state: present
    update_cache: true

- name: Build and install AUR packages
  when: ansible_os_family == "Archlinux"
  loop:
    - teams-for-linux
    - brave-bin
    - grub-customizer
  block:
    - name: Build AUR package
      become: true
      become_user: "{{ user }}"
      ansible.builtin.command:
        cmd: makepkg -sf --noconfirm --needed
        chdir: "/tmp/{{ item }}"
      args:
        creates: "/tmp/{{ item }}/PKGBUILD"

    - name: Install built AUR package
      become: true
      ansible.builtin.shell: |
        pacman -U --noconfirm /tmp/{{ item }}/*.pkg.tar.zst
      args:
        creates: "/usr/bin/{{ item }}"

    - name: Clean up AUR build directory
      become: true
      ansible.builtin.file:
        path: "/tmp/{{ item }}"
        state: absent
