---
- name: Install official packages
  when: ansible_os_family == "Archlinux"
  community.general.pacman:
    name:
      - btop
      - markdownlint
      - spotify-launcher
    state: present
    update_cache: true
