---
- name: Install curl dependency (Debian/Ubuntu)
  ansible.builtin.apt:
    name: curl
    state: present
  when: ansible_os_family == "Debian"

- name: Install curl dependency (Arch Linux)
  community.general.pacman:
    name: curl
    state: present
  when: ansible_os_family == "Archlinux"

- name: Check if cargo is already installed
  ansible.builtin.stat:
    path: "{{ home }}/.cargo/bin/cargo"
  register: cargo_stat

- name: Install Rust and Cargo using rustup
  when: not cargo_stat.stat.exists
  block:
    - name: Download and install Rust via rustup
      become: true
      become_user: "{{ user }}"
      ansible.builtin.shell: |
        set -o pipefail
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
          | sh -s -- -y --no-modify-path --profile minimal
      environment:
        RUSTUP_HOME: "{{ home }}/.rustup"
        CARGO_HOME: "{{ home }}/.cargo"
      args:
        creates: "{{ home }}/.cargo/bin/cargo"
        executable: /bin/bash

    - name: Set default Rust toolchain to stable
      become: true
      become_user: "{{ user }}"
      ansible.builtin.command: "{{ home }}/.cargo/bin/rustup default stable"
      environment:
        RUSTUP_HOME: "{{ home }}/.rustup"
        CARGO_HOME: "{{ home }}/.cargo"
      register: rustup_default
      changed_when: "'unchanged' not in rustup_default.stderr"

- name: Check which cargo packages are installed
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command: "{{ home }}/.cargo/bin/cargo install --list"
  register: installed_packages
  changed_when: false
  failed_when: false

- name: Install Cargo packages
  become: true
  become_user: "{{ user }}"
  community.general.cargo:
    name: "{{ item }}"
    state: present
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ home }}/.cargo/bin"
  when: "item not in installed_packages.stdout"
  loop:
    - git-delta
    - tealdeer
    - zoxide
