---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Install System Packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - build-essential
      - curl
      - gettext
      - fzf
      - git
      - gitlint
      - ripgrep
      - nvidia-settings
      - software-properties-common
      - stow
      - unzip
      - vlc
      - wget
      - xclip
