---
- name: Install system packages and tools (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - bat
      - build-essential
      - curl
      - gettext
      - fzf
      - git
      - git-lfs
      - git-review
      - gitlint
      - lsd
      - ripgrep
      - neofetch
      - net-tools
      - nvidia-settings
      - software-properties-common
      - stow
      - unzip
      - vlc
      - wget
      - xclip
    state: present
    update_cache: true

- name: Install system packages and tools (Arch Linux)
  when: ansible_os_family == "Archlinux"
  community.general.pacman:
    name:
      - bat
      - base-devel
      - curl
      - gettext
      - fzf
      - git
      - git-lfs
      - go
      - lsd
      - ripgrep
      - fastfetch
      - net-tools
      - nvidia-settings
      - openssh
      - stow
      - unzip
      - vlc
      - wget
      - xclip
    state: present

- name: Install yay (Arch Linux)
  when: ansible_os_family == "Archlinux"
  become: true
  become_user: "{{ user }}"
  kewlfft.aur.aur:
    name: yay
    use: makepkg

- name: Ensure .local/bin directory exists
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ home }}/.local/bin"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Check if batcat is installed
  ansible.builtin.stat:
    path: "/usr/bin/batcat"
  register: batcat_check

- name: Create symbolic link for batcat to bat
  ansible.builtin.file:
    src: "/usr/bin/batcat"
    dest: "{{ home }}/.local/bin/bat"
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"
    force: true
  when: batcat_check.stat.exists
