---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Install System Packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - build-essential
      - curl
      - gettext
      - git
      - gitlint
      - global
      - lm-sensors
      - nvidia-settings
      - pandoc
      - software-properties-common
      - stow
      - unzip
      - vlc
      - wget
      - xclip

- name: Yaml linters
  become: true
  ansible.builtin.apt:
    name: ["yamllint", "ansible-lint"]
  tags:
    - core

- name: Install Clang, GCC, Boost
  become: true
  ansible.builtin.apt:
    name:
      - clang
      - clangd
      - gcc
      - g++
      - libboost-all-dev
  tags:
    - core

- name: Java Development Kit
  become: true
  ansible.builtin.apt:
    name: ["default-jdk"]

- name: Install Ranger with deps
  become: true
  ansible.builtin.apt:
    name:
      - ranger
      - caca-utils
      - highlight
      - atool
      - w3m
      - mediainfo
      - lynx
      - ffmpegthumbnailer

- name: Install Neovim deps
  become: true
  ansible.builtin.apt:
    name: ["python3-neovim", "python3-venv", "fzf", "ripgrep", "fd-find"]

- name: Pdf reader
  become: true
  ansible.builtin.apt:
    name: ["zathura"]

- name: Install zsh deps
  become: true
  ansible.builtin.apt:
    name: ["jq", "bc"]
