---
- name: Install System Packages and tools
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - apt-transport-https
    - bat
    - build-essential
    - curl
    - gettext
    - fzf
    - git
    - git-lfs
    - git-review
    - gitlint
    - ripgrep
    - neofetch
    - net-tools
    - nvidia-settings
    - software-properties-common
    - stow
    - unzip
    - vlc
    - wget
    - xclip

- name: Ensure local bin directory exists
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.file:
    path: "{{ home_dir }}/local/bin"
    state: directory
    mode: "0755"

- name: Symbolic link for batcat
  ansible.builtin.file:
    src: "/usr/bin/batcat"
    dest: "{{ home_dir }}/.local/bin/bat"
    state: link
