---
- name: Install system packages and tools (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - bat
      - build-essential
      - curl
      - gettext
      - fzf
      - git
      - git-lfs
      - git-review
      - gitlint
      - lsd
      - ripgrep
      - neofetch
      - net-tools
      - nvidia-settings
      - software-properties-common
      - stow
      - unzip
      - vlc
      - wget
      - xclip
    state: present
    update_cache: true

- name: Install system packages and tools (Arch Linux)
  when: ansible_os_family == "Archlinux"
  community.general.pacman:
    name:
      - bat
      - base-devel
      - curl
      - gettext
      - fzf
      - git
      - git-lfs
      - go
      - lsd
      - ripgrep
      - fastfetch
      - net-tools
      - nvidia-settings
      - openssh
      - stow
      - unzip
      - vlc
      - wget
      - xclip
    state: present

- name: Install yay (Arch Linux)
  when: ansible_os_family == "Archlinux"
  block:
    - name: Check if yay is already installed
      ansible.builtin.command: yay --version
      register: yay_check
      failed_when: false
      changed_when: false

    - name: Install yay from AUR
      when: yay_check.rc != 0
      block:
        - name: Install base-devel and git (required for building AUR packages)
          ansible.builtin.pacman:
            name:
              - base-devel
              - git
            state: present

        - name: Remove old yay build directory
          ansible.builtin.file:
            path: /tmp/yay
            state: absent

        - name: Clone yay repository
          become: true
          become_user: "{{ user }}"
          ansible.builtin.git:
            repo: https://aur.archlinux.org/yay.git
            dest: /tmp/yay
            update: true
            version: master

        - name: Build yay package
          become: true
          become_user: "{{ user }}"
          ansible.builtin.command: makepkg -sf --noconfirm --needed
          args:
            chdir: /tmp/yay
          register: yay_build
          changed_when: yay_build.rc == 0

        - name: Install yay package
          ansible.builtin.command: pacman -U --noconfirm /tmp/yay/*.pkg.tar.zst
          args:
            creates: /usr/sbin/yay

        - name: Clean up yay build directory
          ansible.builtin.file:
            path: /tmp/yay
            state: absent

- name: Ensure .local/bin directory exists
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ home }}/.local/bin"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Check if batcat is installed
  ansible.builtin.stat:
    path: "/usr/bin/batcat"
  register: batcat_check

- name: Create symbolic link for batcat to bat
  ansible.builtin.file:
    src: "/usr/bin/batcat"
    dest: "{{ home }}/.local/bin/bat"
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"
    force: true
  when: batcat_check.stat.exists
