---
- name: Install cpp packages
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - autoconf
    - automake
    - clang
    - clang-format
    - clang-tidy
    - clangd
    - cmake
    - meson
    - gcc
    - g++
    - libboost-all-dev
