---
- name: Install cpp packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - autoconf
      - automake
      - clang
      - clang-format
      - clang-tidy
      - clangd
      - clazy
      - cmake
      - cppcheck
      - meson
      - gcc
      - gdb
      - g++
      - libboost-all-dev
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install cpp packages (Arch Linux)
  community.general.pacman:
    name:
      - autoconf
      - automake
      - clang
      - cmake
      - cppcheck
      - meson
      - gcc
      - gdb
      - boost
    state: present
  when: ansible_os_family == "Archlinux"
