---
- name: Install stow
  ansible.builtin.apt:
    name: stow
    state: present
    update_cache: true

- name: Check if dotfiles directory exists
  ansible.builtin.stat:
    path: "{{ home_dir }}/dotfiles"
  register: dotfiles_dir

- name: Clone dotfiles repository
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.git:
    repo: "git@github.com:FBorowiec/dotfiles.git"
    dest: "{{ home_dir }}/dotfiles"
    version: main
    force: false
  when: not dotfiles_dir.stat.exists

- name: dotfiles install
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.command: "./install"
  args:
    chdir: "{{ home_dir }}/dotfiles"
  register: dotfiles_install
  changed_when: dotfiles_install.rc == 0
  failed_when: dotfiles_install.rc != 0
