---
- name: Install Stow
  ansible.builtin.apt:
    name:
      - stow

- name: "Check dotfiles dir exists"
  ansible.builtin.stat:
    path: "{{ home_dir }}/dotfiles"
  register: dotfiles

- name: Clone the dotfiles repo
  become_user: "{{ main_user }}"
  ansible.builtin.git:
    repo: "git@github.com:FBorowiec/dotfiles.git"
    dest: "{{ home_dir }}/dotfiles"
    version: main
    key_file: "{{ dest_key }}"
  when: not dotfiles.stat.exists

- name: Stow dotfiles
  become_user: "{{ main_user }}"
  ansible.builtin.command: "cd {{ home_dir }}/dotfiles && ./install"
  register: dotfiles_install
  changed_when: dotfiles_install.rc != 0
  failed_when: dotfiles_install.rc != 0
  when: not dotfiles.stat.exists
