---
- name: Install stow (Debian/Ubuntu)
  ansible.builtin.apt:
    name: stow
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install stow (Arch Linux)
  community.general.pacman:
    name:
      - stow
      - openssh
    state: present
  when: ansible_os_family == "Archlinux"

- name: Check if dotfiles directory exists
  ansible.builtin.stat:
    path: "{{ home }}/dotfiles"
  register: dotfiles_dir

- name: Clone dotfiles repository
  become: true
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "git@github.com:FBorowiec/dotfiles.git"
    dest: "{{ home }}/dotfiles"
    version: main
    force: false
  when: not dotfiles_dir.stat.exists

- name: dotfiles install
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command: "./install"
  args:
    chdir: "{{ home }}/dotfiles"
  register: dotfiles_install
  changed_when: dotfiles_install.rc == 0
  failed_when: dotfiles_install.rc != 0

- name: Enable auto-display.service for user
  become: true
  become_user: "{{ user }}"
  when: not container_check.stat.exists
  ansible.builtin.systemd:
    name: auto-display.service
    enabled: true
    scope: user
