---
- name: X/fonts - Copy fonts directory
  become_user: "{{ main_user }}"
  ansible.builtin.copy:
    src: files/fonts
    dest: "{{ home_dir }}/.local/share/fonts"
    mode: "0755"

- name: Fetch all releases for Nerd Fonts
  ansible.builtin.uri:
    url: "https://api.github.com/repos/ryanoasis/nerd-fonts/releases"
    return_content: true
    method: GET
    headers:
      Accept: "application/vnd.github.v3+json"
  register: nerd_fonts_releases

- name: Extract the most recent release tag for Nerd Fonts
  ansible.builtin.set_fact:
    nerd_fonts_latest_version: "{{ (nerd_fonts_releases.json | sort(attribute='published_at') | last).tag_name }}"

- name: Download fonts zip file
  become_user: "{{ main_user }}"
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ nerd_fonts_latest_version }}/3270.zip"
    dest: "{{ home_dir }}/3270.zip"
    mode: "0664"

- name: Unzip fonts
  become_user: "{{ main_user }}"
  ansible.builtin.unarchive:
    src: "{{ home_dir }}/3270.zip"
    dest: "{{ home_dir }}/.local/share/fonts"
    remote_src: true

- name: Remove zip file
  become_user: "{{ main_user }}"
  ansible.builtin.file:
    path:
      dest: "{{ home_dir }}/3270.zip"
    state: absent

- name: Install additional fonts
  ansible.builtin.apt:
    name:
      - fonts-powerline
      - fonts-font-awesome
      - fonts-firacode
      - fonts-hack-ttf
      - fonts-ubuntu

- name: X/fonts - Refresh font cache
  ansible.builtin.command: fc-cache -fv
  register: refreshed_font_cache
  changed_when: refreshed_font_cache.rc != 0
  failed_when: refreshed_font_cache.rc != 0
