---
- name: Install Lua and LuaRocks (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - lua5.4
      - luarocks
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install Lua and LuaRocks (Arch Linux)
  community.general.pacman:
    name:
      - lua
      - luarocks
    state: present
  when: ansible_os_family == "Archlinux"

- name: Check if luacheck is already installed
  ansible.builtin.command: luarocks list luacheck
  register: luacheck_check
  changed_when: false
  failed_when: false

- name: Install luacheck via luarocks
  ansible.builtin.command: luarocks install luacheck
  register: luacheck_install
  changed_when: "'Installing' in luacheck_install.stdout"
  failed_when: luacheck_install.rc != 0
  when: "'luacheck' not in luacheck_check.stdout"
  become: true
