---
- name: Install lua
  ansible.builtin.apt:
    name: luarocks

- name: Install luacheck
  ansible.builtin.command: luarocks install luacheck
  register: luacheck_install
  changed_when: luacheck_install.rc != 0
  failed_when: luacheck_install.rc != 0
  retries: 3
  delay: 10
