---
- name: Install Neovim deps
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - python3-neovim
    - python3-venv
    - fzf
    - ripgrep
    - fd-find

- name: Clone Neovim
  become: true
  become_user: "{{ user }}"
  retries: 3
  delay: 10
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ home }}/neovim"
    version: master
    depth: 1

- name: Install build requirements for neovim
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - ninja-build
    - gettext
    - cmake
    - unzip
    - curl
    - build-essential
    - luarocks

- name: Build neovim
  become_user: "{{ user }}"
  ansible.builtin.command: "make CMAKE_BUILD_TYPE=RelWithDebInfo"
  register: build_neovim
  changed_when: build_neovim.rc != 0
  failed_when: build_neovim.rc != 0
  args:
    chdir: "{{ home }}/neovim"

- name: Install neovim
  ansible.builtin.command: "make install"
  register: install_neovim
  changed_when: install_neovim.rc != 0
  failed_when: install_neovim.rc != 0
  args:
    chdir: "{{ home }}/neovim"

- name: Install Telescope deps
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - chafa # media-preview
