---
- name: Install npm
  ansible.builtin.apt:
    name: ["npm"]

- name: Install n
  ansible.builtin.npm:
    name: n
    global: true

- name: Install latest n
  ansible.builtin.shell: n latest

- name: Install npm packages
  ansible.builtin.npm:
    name: "{{ item }}"
    global: true
  loop:
    - yarn
    - typescript
    - ts-node
    - emojione
    - live-server
