---
- name: Install npm
  community.general.npm:
    name: "npm"
    global: true

- name: Install n
  community.general.npm:
    name: "n"
    global: true

- name: Install latest n
  ansible.builtin.shell: n latest

- name: Install npm packages
  community.general.npm:
    name: "{{ item }}"
    global: true
  loop:
    - "yarn"
    - "typescript"
    - "ts-node"
    - "emojione"
    - "live-server"
