---
- name: Install additional python packages
  ansible.builtin.apt:
    name:
      - python3-dev
      - python3-pip

- name: Ensure pipx is installed
  ansible.builtin.apt:
    name: pipx
    update_cache: true
    state: present

- name: Ensure pipx is in PATH
  ansible.builtin.command: "pipx ensurepath"

- name: Install yamllint
  community.general.pipx:
    name: "yamllint"

- name: Install sqlfluff
  community.general.pipx:
    name: "sqlfluff"

- name: Install zsh deps
  community.general.pipx:
    name: thefuck
