---
- name: Install additional python packages
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - python3-dev
    - python3-pip

- name: Ensure pipx is installed
  ansible.builtin.apt:
    name: pipx
    update_cache: true
    state: present

- name: Ensure pipx is in PATH
  ansible.builtin.command: "pipx ensurepath"

- name: Install some pipx tools
  community.general.pipx:
    name: "{{ item }}"
  loop:
    - yamllint
    - sqlfluff

- name: Install zsh deps
  community.general.pipx:
    name: thefuck
