---
- name: Install Python development packages
  ansible.builtin.apt:
    name:
      - python3-dev
      - python3-pip
      - pipx
    state: present
    update_cache: true

- name: Check if pipx is properly configured
  become: true
  become_user: "{{ user }}"
  ansible.builtin.stat:
    path: "{{ home }}/.local/bin/pipx"
  register: pipx_check

- name: Check which pipx tools are already installed
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command: pipx list --short
  register: pipx_installed
  changed_when: false
  failed_when: false
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ home }}/.local/bin"

- name: Install pipx development tools
  become: true
  become_user: "{{ user }}"
  community.general.pipx:
    name: "{{ item }}"
    state: present
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ home }}/.local/bin"
  when: "item not in pipx_installed.stdout"
  loop:
    - yamllint
    - sqlfluff
    - git-filter-repo
    - thefuck
  register: pipx_installs
