---
- name: Install snap packages
  when:
    - ansible_os_family == "Debian"
    - not container_check.stat.exists
  community.general.snap:
    name:
      - spotify
      - btop
      - mdl
      - brave
      - teams-for-linux
    state: present
