---
- name: Ensure .ssh directory exists.
  become_user: "{{ main_user }}"
  ansible.builtin.file:
    dest: "{{ dest_key | dirname }}"
    mode: "0700"
    state: directory

- name: Install ssh key
  become_user: "{{ main_user }}"
  ansible.builtin.copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: "0600"

- name: Install ssh key public
  become_user: "{{ main_user }}"
  ansible.builtin.copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: "0644"
