---
- name: Ensure .ssh directory exists.
  become_user: "{{ main_user }}"
  ansible.builtin.file:
    dest: "{{ home_dir }}/.ssh"
    mode: "0700"
    state: directory

- name: Install ssh key
  become_user: "{{ main_user }}"
  ansible.builtin.copy:
    src: ".ssh/id_ed25519"
    dest: "{{ home_dir }}/.ssh/id_ed25519"
    mode: "0600"

- name: Install ssh key public
  become_user: "{{ main_user }}"
  ansible.builtin.copy:
    src: ".ssh/id_ed25519.pub"
    dest: "{{ home_dir }}/.ssh/id_ed25519.pub"
    mode: "0644"
