---
- name: Install tmux deps
  ansible.builtin.apt:
    name: "tmux"

- name: Clone tpm plugins
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "{{ home }}/.tmux/plugins/tpm"
    version: master
    depth: 1
