---
- name: Install official packages
  when: ansible_os_family == "Archlinux"
  community.general.pacman:
    name:
      - base-devel
      - btop
      - markdownlint
      - spotify-launcher
    state: present
    update_cache: true

- name: Install paru AUR helper
  become: true
  become_user: "{{ user }}"
  when: ansible_os_family == "Archlinux"
  ansible.builtin.shell: |
    cd /tmp
    git clone https://aur.archlinux.org/paru.git
    cd paru
    makepkg -si --noconfirm
    cd ..
    rm -rf paru

- name: Install community maintained packages
  become: true
  become_user: "{{ user }}"
  when: ansible_os_family == "Archlinux"
  ansible.builtin.command: paru -S --noconfirm --needed {{ item }}
  loop:
    - teams-for-linux
    - brave-bin
    - grub-customizer
# - name: Install AUR packages with makepkg
#   ansible.builtin.shell: |
#     cd /tmp
#     if [ ! -d "{{ item }}" ]; then
#       git clone https://aur.archlinux.org/{{ item }}.git
#     fi
#     cd {{ item }}
#     makepkg -si --noconfirm --needed
#     cd ..
#     rm -rf {{ item }}
#   become: true
#   become_user: "{{ user }}"
#   loop:
#     - teams-for-linux
#     - brave-bin
#     - grub-customizer
#   args:
#     creates: /usr/sbin/{{ item }}
#   when: ansible_os_family == "Archlinux"
