---
- name: Install zsh and dependencies (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - zsh
      - jq
      - bc
      - poppler-utils
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install zsh and dependencies (Arch Linux)
  community.general.pacman:
    name:
      - zsh
      - jq
      - bc
      - poppler
    state: present
  when: ansible_os_family == "Archlinux"

- name: Check current user shell
  ansible.builtin.command: getent passwd {{ user }}
  register: current_shell
  changed_when: false

- name: Check if oh-my-zsh exists
  ansible.builtin.stat:
    path: "{{ home }}/.oh-my-zsh"
  register: ohmyzsh_exists

- name: Install oh-my-zsh
  become: true
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{ home }}/.oh-my-zsh"
    version: master
    depth: 1
  when: not ohmyzsh_exists.stat.exists

- name: Install zsh plugins and themes
  become: true
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ home }}/.oh-my-zsh/custom/{{ item.type }}/{{ item.name }}"
    version: "{{ item.version }}"
    depth: 1
  loop:
    - repo: "https://github.com/romkatv/powerlevel10k.git"
      type: "themes"
      name: "powerlevel10k"
      version: "master"
    - repo: "https://github.com/marlonrichert/zsh-autocomplete"
      type: "plugins"
      name: "zsh-autocomplete"
      version: "main"
    - repo: "https://github.com/zsh-users/zsh-autosuggestions"
      type: "plugins"
      name: "zsh-autosuggestions"
      version: "master"
    - repo: "https://github.com/supercrabtree/k"
      type: "plugins"
      name: "k"
      version: "master"
    - repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
      type: "plugins"
      name: "zsh-syntax-highlighting"
      version: "master"
    - repo: "https://github.com/Aloxaf/fzf-tab"
      type: "plugins"
      name: "fzf-tab"
      version: "master"
    - repo: "https://github.com/jeffreytse/zsh-vi-mode"
      type: "plugins"
      name: "zsh-vi-mode"
      version: "master"
  register: plugin_installs
  when: not ohmyzsh_exists.stat.exists

- name: Change default shell to zsh
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
  become: true
  when: "'/usr/bin/zsh' not in current_shell.stdout"

- name: Ensure zsh is launched from bashrc
  become: true
  become_user: "{{ user }}"
  ansible.builtin.lineinfile:
    path: "{{ home }}/.bashrc"
    line: "exec zsh && exit"
    regexp: "^(exec )?zsh.*"
    state: present
    create: true
    mode: "0644"
    backup: true
